### ISSUE TITLE
Error 409

### ISSUE THREAD

**Issue by Stefinho86** [AstraeLabs/VibraVid#11]
![Screenshot 2024-01-08 125507](https://github.com/Ghost6446/StreamingCommunity_api/assets/133981343/7a7aafe9-725a-4585-b9b4-737e4b9ee89b)
Ciao, non scarica il contenuto come da foto allegata.

**Comment by Arrowar** [comment]
Scarica la nuova versione

**Comment by Stefinho86** [comment]
l'avevo provato con versione 0.7.0. ed esce l'errore indicato.

**Comment by Arrowar** [comment]
Ok appena ho tempo guardo

**Comment by Arrowar** [comment]
> l'avevo provato con versione 0.7.0. ed esce l'errore indicato.

Scarica dall'ultima release, ho provato e funziona, quindi elimina quella vecchia e scarica quella nuova.
