### ISSUE TITLE
Error with [Win 7]

### ISSUE THREAD

**Issue by jonnyprogamer** [AstraeLabs/VibraVid#114]
Salve, sto provando ad avviare lo script dal source dato che dal runtime non si avvia per mancanza di DLL (il tool che è usato per impacchettare Python non supporta Win 7), ho già ffmpeg nel %PATH% di Windows e tutti i requisiti sono stati installati, ma mi escono fuori vari errori, ecco l'output:

![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/93492418/3a30e351-2e13-46c1-b583-5962c17336a0)

```
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    from Src.Api import (
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Api\__init__.py",
line 3, in <module>
    from .film import download_film
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Api\film.py", line
 10, in <module>
    from Src.Lib.FFmpeg.my_m3u8 import Downloader
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Lib\FFmpeg\__init_
_.py", line 3, in <module>
    from .util.installer import check_ffmpeg
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Lib\FFmpeg\util\__
init__.py", line 3, in <module>
    from .helper import (
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Lib\FFmpeg\util\he
lper.py", line 95, in <module>
    def format_duration(seconds: float) -> list[int, int, int]:
TypeError: 'type' object is not subscriptable
```

Da quel che vedo penso che sia perchè sto usando Python 3.8 invece di 3.11 o successivi (come richiesto dal Readme), ma l'ultima versione di Python che supporta Win 7 è la 3.8
Sarebbe possibile far girare questo script su Python 3.8 in modo che funzioni anche su Windows 7? Grazie! (volevo entrare sul discord per discutere del problema ma il link è scaduto)

**Comment by Arrowar** [comment]
Ciao si potrebbe essere, se fai ffmpeg sul terminale esce qualcosa ? Prova per il momento la versione pre release sempre sulla 1.0 che forse funziona.https://discord.gg/zjfsD36JHD, lo so scade sempre nonostanze mette no expire. Versione compilata su win 11: https://github.com/Ghost6446/StreamingCommunity_api/releases/download/v1.0.0/StreamingCommunity_api_win.rar

**Comment by jonnyprogamer** [comment]
Si ffmpeg funziona, ora entro nel discord.

![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/93492418/2c7f31b4-915c-47e4-89ef-725e15ef4b66)

**Comment by jonnyprogamer** [comment]
La versione di "pyinstaller" usata non funziona su Win 7:

![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/93492418/fd530103-cb3a-43d6-9714-797794098567)

**Comment by Arrowar** [comment]
Se hai vs code apri C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Lib\FFmpeg\util\helper.py e guarda se vs code rivela errori, teoricamente dovrebbe essere in quel file il problema.

**Comment by jonnyprogamer** [comment]
Si, ci sono alcuni errori, il primo sembra che i moduli console.py e config.py non vengano trovati dal helper.py, questo perchè siamo in una sub directory (VSCode dava questo errore: `Import "Src.Util.console" could not be resolved`), ed ho modificato in questo modo:
da:
```
from Src.Util.console import console
from Src.Util.config import config_manager
```

a:
```
from ....Util.config import config_manager
from ....Util.console import console
```

poi mi sembrava che la funzione "list" non è usata correttamente, VSCode dava questo errore: (`
Built-in mutable sequence.
If no argument is given, the constructor creates a new empty list. The argument must be an iterable if specified.
Subscript for class "list" will generate runtime exception; enclose type annotation in quotes
`)

perciò l'ho modificata in questo modo:
da: `def format_duration(seconds: float) -> list[int, int, int]:`
a: `def format_duration(seconds: float) -> List[int]:`

e poi il return del valore:
da: `return int(hours), int(minutes), int(seconds)`
a: `return [int(hours), int(minutes), int(seconds)]`

ho importato da "typing" List e Dict, ed ho sistemato anche le altre righe nel file (che usavano list) che portavano lo stesso problema.

Non so nulla di Python quindi può darsi che quello che ho fatto sia completamente errato, ho solo seguito quello che mi diceva VSCode e la documentazione 😂

Comunque ora mi da un errore sul file "os.py":
```
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    from Src.Api import (
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Api\__init__.py",
line 3, in <module>
    from .film import download_film
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Api\film.py", line
 10, in <module>
    from Src.Lib.FFmpeg.my_m3u8 import Downloader
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Lib\FFmpeg\__init_
_.py", line 3, in <module>
    from .util.installer import check_ffmpeg
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Lib\FFmpeg\util\__
init__.py", line 15, in <module>
    from .installer import check_ffmpeg
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Lib\FFmpeg\util\in
staller.py", line 16, in <module>
    from Src.Util.os import decompress_file
  File "C:\Users\jonnyprogamer\Desktop\Streaming Community Downloader\StreamingCommunity_api-main\Src\Util\os.py", line
226, in <module>
    def decode_bytes(bytes_data: bytes, encodings_to_try: list[str] = None) -> str:
TypeError: 'type' object is not subscriptable
```

**Comment by Arrowar** [comment]
Ok che film o serie / ep stavi scaricando?

**Comment by jonnyprogamer** [comment]
No non mi si avvia proprio il programma, ora provo a smanettare con il file "os.py"

**Comment by Arrowar** [comment]
Certo prova a togliere tutti i :int :list ... e -> int, -> str per vedere se è quello che gli da problemi.

**Comment by Arrowar** [comment]
Stano che con python 3.8 dia così  tanti problemi.

**Comment by jonnyprogamer** [comment]
Nel modulo typing non esiste "l'Unpack" che viene richiesto da "my_request.py" 😢

**Comment by Ghost6446** [comment]
Se lo rimuovi parte ?

**Comment by Arrowar** [comment]
> Nel modulo typing non esiste "l'Unpack" che viene richiesto da "my_request.py" 😢

Allora ho fatto delle prova con la version di pyton 3.7, o si rimuove tutti i tipi delle variabili, altrimenti non c'è modo di farlo partire. TI consiglio di scaricare il installare almeno una version >= 3.10. Prova a seguire questa guida per scaricare le versioni successive: https://github.com/adang1345/PythonWin7

**Comment by jonnyprogamer** [comment]
Sto modificando il codice passo passo per togliere tutti gli errori, al momento sono arrivato finalmente a sistemare il file "useragent.py", non so perchè vi siete creati una libreria che fa richieste HTTP, la ho cambiata con quella standard di Python e sono riuscito a scaricare la lista di User Agent

**Comment by jonnyprogamer** [comment]
In caso fallisco provo ad installare Python tramite quel metodo (sapevo che esisteva ma ho evitato di usarlo)

**Comment by jonnyprogamer** [comment]
Il codice modificato di useragent.py:

```
import requests

def get_browser_user_agents_online(browser: str) -> List[str]:
    """
    Retrieve browser user agent strings from a website using Python requests library.

    Args:
        browser (str): The name of the browser (e.g., 'chrome', 'firefox', 'safari').
        proxies (dict, optional): Dictionary containing proxy settings (e.g., {'http': 'http://proxy.example.com:8080'}).

    Returns:
        List[str]: List of user agent strings for the specified browser.
    """
    url = f"https://useragentstring.com/pages/{browser}/"

    try:
        response = requests.get(url) 
        response.raise_for_status()

        html_content = response.text
        browser_user_agents = re.findall(r"<a href=\'/.*?>(.+?)</a>", html_content, re.UNICODE)
        filtered_user_agents = [ua for ua in browser_user_agents if "more" not in ua.lower()]

        if not filtered_user_agents:
            logging.warning(f"No valid user agents found for '{browser}'.")
        
        return filtered_user_agents
    
    except requests.RequestException as e:
        logging.error(f"Failed to fetch user agents for '{browser}': {str(e)}")
        return []
```

**Comment by Arrowar** [comment]
> Sto modificando il codice passo passo per togliere tutti gli errori, al momento sono arrivato finalmente a sistemare il file "useragent.py", non so perchè vi siete creati una libreria che fa richieste HTTP, la ho cambiata con quella standard di Python e sono riuscito a scaricare la lista di User Agent

Si si non c'è problema, ho provato a farne il più facile perché mi andava di fare ed è risultata anche un pelino più veloce su una media di richieste. Ora la sto testando per tutte le richieste rimuovendo requests ma uscirà nella prossima versione.

**Comment by Arrowar** [comment]
> > Sto modificando il codice passo passo per togliere tutti gli errori, al momento sono arrivato finalmente a sistemare il file "useragent.py", non so perchè vi siete creati una libreria che fa richieste HTTP, la ho cambiata con quella standard di Python e sono riuscito a scaricare la lista di User Agent
> 
> Si si non c'è problema, ho provato a farla perché mi andava di farla e capire come funzionava l'originale, ed è risultata anche un pelino più veloce su una media di richieste. Ora la sto testando per tutte le richieste rimuovendo requests completamente, ma uscirà nella prossima versione. Comunque il nome che gli ho dato è sempre requests così se non funziona più basta cancellare il file e gli import.

**Comment by Arrowar** [comment]
> In caso fallisco provo ad installare Python tramite quel metodo (sapevo che esisteva ma ho evitato di usarlo)

Hanno implementato delle funzioni nuove come è normale che sia, dimmi se ci riesci.

**Comment by Arrowar** [comment]
> Il codice modificato di useragent.py:
> 
> ```
> import requests
> 
> def get_browser_user_agents_online(browser: str) -> List[str]:
>     """
>     Retrieve browser user agent strings from a website using Python requests library.
> 
>     Args:
>         browser (str): The name of the browser (e.g., 'chrome', 'firefox', 'safari').
>         proxies (dict, optional): Dictionary containing proxy settings (e.g., {'http': 'http://proxy.example.com:8080'}).
> 
>     Returns:
>         List[str]: List of user agent strings for the specified browser.
>     """
>     url = f"https://useragentstring.com/pages/{browser}/"
> 
>     try:
>         response = requests.get(url) 
>         response.raise_for_status()
> 
>         html_content = response.text
>         browser_user_agents = re.findall(r"<a href=\'/.*?>(.+?)</a>", html_content, re.UNICODE)
>         filtered_user_agents = [ua for ua in browser_user_agents if "more" not in ua.lower()]
> 
>         if not filtered_user_agents:
>             logging.warning(f"No valid user agents found for '{browser}'.")
>         
>         return filtered_user_agents
>     
>     except requests.RequestException as e:
>         logging.error(f"Failed to fetch user agents for '{browser}': {str(e)}")
>         return []
> ```

Basta che guardi le versioni vecchie, prima delle 1.0, il codice usa la libreria random_user_agent ma aveva qualche problema con pyinstaller, quindi mi sono fatto anche quella.

**Comment by jonnyprogamer** [comment]
Ah capito, ora  sono riuscito ad avviare il programma, mi chiede di installare Python 3.11 o successivo, provo a rimuovere il check e vedo che succede:

python run.py
Insert category (0: Film/Series, 1: Anime): [0/1] (0): 0
[19:39:16] Install python version > 3.11                              run.py:59

**Comment by jonnyprogamer** [comment]
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/93492418/1ecec3bb-54d2-4772-b512-a09e0ad6e993)

C'è l'ho fatta a far partire il programma ahahaha, bastava rinchiudere le varie "list" e "tuple" in site.py con la single quote `'`
Probabilmente riesco a far girare anche la libreria personalizzata adesso 👍

**Comment by Arrowar** [comment]
> ![image](https://private-user-images.githubusercontent.com/93492418/324195421-1ecec3bb-54d2-4772-b512-a09e0ad6e993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzU0MzQsIm5iZiI6MTcxMzYzNTEzNCwicGF0aCI6Ii85MzQ5MjQxOC8zMjQxOTU0MjEtMWVjZWMzYmItNTRkMi00NzcyLWI1MTItYTA5ZTBhZDZlOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE3NDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MzQ5ZGNjMjBjNzM1MTg4ZGZjMmRjZDhkZmE2ZTQ1OTNlODlhMWJjMmZkYzdlZmJiN2E3MzRlZWI2MWIyZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cNgp7nZP_NyXrXY6Za1zEEJZVLXkCEJZ802c5tV-ezg)
> 
> C'è l'ho fatta a far partire il programma ahahaha, bastava rinchiudere le varie "list" e "tuple" in site.py con la single quote `'` Probabilmente riesco a far girare anche la libreria personalizzata adesso 👍

Perfetto, questa è un'ottima notizia . 😁

**Comment by jonnyprogamer** [comment]
Il download procede anche senza problemi, ora controllo anche se fa il join e poi in caso vedo se riesco a fare andare la libreria my_request, 👍

**Comment by Arrowar** [comment]
Si dovrebbe andare tutto, se trovi problemi di stuttering ogni tanto è normale, sto finendo di scrivere un'altra libreria ma ci vorrà un po' di tempo.

**Comment by jonnyprogamer** [comment]
Yes il download funziona perfettamente, In caso ti dico tutte le modifiche che ho fatto così puoi controllarle e inserirle per la prossima versione, ora provo a far andare la libreria 😂

**Comment by jonnyprogamer** [comment]
Grazie per il supporto, in effetti il problema "grave" è solo "l''Unpack" in my_request.py, che non esiste in 3.8, ma credo di poterlo aggirare

**Comment by jonnyprogamer** [comment]
Non sono capace di modificare la libreria HTTP quindi per ora la lascio stare, in ogni caso penso che quella sia l'unica cosa da modificare un pò per farla andare su Win 7, e forse utilizzare una versione più vecchia di pyinstaller, oltre a questo funziona tutto (l'ultima versione di ffmpeg gira ancora sul 7) nessun problema tanto fa le stesse cose di requests, ffmpeg si dovrebbero funzionare anche le versioni vecchie, forse se lo aggiorni, va un pelino più veloce.

**Comment by Arrowar** [comment]
Di niente, si unpack serve per avere quando chiami per esempio get tutti i metodi della classe reuqests, ma teoricamente dovrebbe esserci una soluzioni, per tutti gli altri avevi provato ad importarli da typing e sempre funzionare. Errore mio che quando ho fatti alcuni file invece di importarli da typing gli go usati normalmente, ma effettivamente c'era un motivo.

**Comment by Arrowar** [comment]
> Yes il download funziona perfettamente, In caso ti dico tutte le modifiche che ho fatto così puoi controllarle e inserirle per la prossima versione, ora provo a far andare la libreria 😂

Gentilissimo se riesci.  😀😀

**Comment by jonnyprogamer** [comment]
> Di niente, si unpack serve per avere quando chiami per esempio get tutti i metodi della classe reuqests, ma teoricamente dovrebbe esserci una soluzioni, per tutti gli altri avevi provato ad importarli da typing e sempre funzionare. Errore mio che quando ho fatti alcuni file invece di importarli da typing gli go usati normalmente, ma effettivamente c'era un motivo.

Si penso che in questa versione non si poteva fare, comunque ora ti elenco tutte le modifiche

> Gentilissimo se riesci

Prego non c'è di che, siamo su GitHub alla fine, e pure giusto contribuire ogni tanto, anche con poca esperienza ahaha 😂

Inoltre ti consiglio di aggiungere un controllo se l'utente preme CTRL + C al run.py, tipo così:
```
       try:
            # If no arguments are provided, ask the user to input the category, if nothing insert return 0
            category = msg.ask("[cyan]Insert category [white]([red]0[white]: [bold magenta]Film/Series[white], [red]1[white]: [bold magenta]Anime[white])[white]:[/cyan]", choices={"0": "", "1": ""}, default="0")

            if category == '0':
                run_function(main_film_series, CLOSE_CONSOLE)

            elif category == '1':
                run_function(main_anime, CLOSE_CONSOLE)

            else:
                console.print("[red]Invalid category, you need to insert 0 or 1.")
                sys.exit(0)
        except KeyboardInterrupt:
            console.print("\n[cyan]Application interrupted by the user.")
            sys.exit(0)
```

In modo da non generare un errore in caso si termini l'app in quel modo

**Comment by Arrowar** [comment]
Per risolvere unpack prova questa soluzione degli import: https://github.com/python/mypy/issues/13981, si ctrl+c lo aggiungerò sicuramente.

**Comment by jonnyprogamer** [comment]
# Modifications to make the program run on Wndows 7:

# 1\) run.py:
Edit, comment out or delete the Python version check:
Example:
```
if sys.version_info < (3, 8):
        console.log("Install python version >= 3.8.10")
        sys.exit(0)
```

# 2\) StreamingCommunity_api-main\Src\Lib\FFmpeg\util\helper.py
Edit the import of local libraries to correctly link to them:
Change:
```
from Src.Util.console import console
from Src.Util.config import config_manager
```

To:
```
from ....Util.config import config_manager
from ....Util.console import console
```

Add -> `from typing import List, Dict`

Go to line `95`, change: `list[int, int, int]` -> `List[int]`
Go to line `109`, change: `return int(hours), int(minutes), int(seconds)` -> `return [int(hours), int(minutes), int(seconds)]`
Change: `list[dict[str, str]]` -> `List[Dict[str, str]]` for all the times you find it (should be 3)

# 3\) StreamingCommunity_api-main\Src\Util\os.py
Go to line `228`, this syntax is not supported in `Python 3.8`, we can use `Optional[str]` and `List[str]` to get around it.
Change:
`def decode_bytes(bytes_data: bytes, encodings_to_try: list[str] = None) -> str:`

To:
`def decode_bytes(bytes_data: bytes, encodings_to_try: Optional[List[str]] = None) -> Optional[str]:`

# 4\) StreamingCommunity_api-main\Src\Lib\Request\user_agent.py
Here we will need to bypass the custom Request library and use Python built in one (for now at least)
We can do so by changing the code like this:

From:
```
# Internal utilities
from .my_requests import request

def get_browser_user_agents_online(browser: str) -> List[str]:
    """
    Retrieve browser user agent strings from a website.

    Args:
        browser (str): The name of the browser (e.g., 'chrome', 'firefox', 'safari').

    Returns:
        List[str]: List of user agent strings for the specified browser.
    """
    url = f"https://useragentstring.com/pages/{browser}/"

    try:

        # Make request and find all user agents
        html = request.get(url).text
        browser_user_agents = re.findall(r"<a href=\'/.*?>(.+?)</a>", html, re.UNICODE)
        return [ua for ua in browser_user_agents if "more" not in ua.lower()]
    
    except Exception as e:
        logging.error(f"Failed to fetch user agents for '{browser}': {str(e)}")
        return []
```

To:
```
import requests

# Internal utilities, bypassed by using standard Python requests lib
# from .my_requests import request

# Modified the functions to use Python built in "requests", compatible with Windows 7 without messing the custom implementation in "my_requests.py"
def get_browser_user_agents_online(browser: str) -> List[str]:
    """
    Retrieve browser user agent strings from a website using Python requests library.

    Args:
        browser (str): The name of the browser (e.g., 'chrome', 'firefox', 'safari').
        proxies (dict, optional): Dictionary containing proxy settings (e.g., {'http': 'http://proxy.example.com:8080'}).

    Returns:
        List[str]: List of user agent strings for the specified browser.
    """
    url = f"https://useragentstring.com/pages/{browser}/"

    try:
        response = requests.get(url) 
        response.raise_for_status()

        html_content = response.text
        browser_user_agents = re.findall(r"<a href=\'/.*?>(.+?)</a>", html_content, re.UNICODE)
        filtered_user_agents = [ua for ua in browser_user_agents if "more" not in ua.lower()]

        if not filtered_user_agents:
            logging.warning(f"No valid user agents found for '{browser}'.")
        
        return filtered_user_agents
    
    except requests.RequestException as e:
        logging.error(f"Failed to fetch user agents for '{browser}': {str(e)}")
        return []
```

# 5\) StreamingCommunity_api-main\Src\Api\series.py
Add: `from typing import List`
Change: `list[int]: -> List[int]:`

# 6\) StreamingCommunity_api-main\Src\Api\site.py
Add: `from typing import Tuple`
Change: `tuple[str, str] -> Tuple[str, str]`

# 7\) Run Windows Updates in the target OS
The User must make sure that all the important updates (and up to the latest 2020 Cumulative updates) are installed to avoid TLS issues, this is because of Windows 7 not enforcing TLS 1.2 by default.
Having Windows Update fully working also ensures that the OS Trusted Certificates Store gets udpated regularly by Microsoft servers.
To make sure that TLS 1.2 is enabled, follow this procedure:
1) Make sure you have updated Internet Explorer to the latest version (11)
2) Go to Internet Options -> Advanced -> check "Use TLS 1.1" and "Use TLS 1.2"
Screenshot:
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/93492418/4ee6c237-534c-4ab6-9b8d-5431911f228e)
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/93492418/7033591c-77f1-4ee5-9cd8-d6150407229f)


NOTE: IF INTERNET EXPLORER IS NOT UPDATED, these Registry values won't take ANY effect, this also requires update "KB3140245"
Microsoft Knowledge Article: https://support.microsoft.com/kb/3140245

3) After all the latest Windows Updates are installed, download and run (linked in KB3140245 article) -> https://download.microsoft.com/download/0/6/5/0658B1A7-6D2E-474F-BC2C-D69E5B9E9A68/MicrosoftEasyFix51044.msi
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/93492418/1a5ee178-bad9-4551-9fd6-2e684aa99573)

Or, to do it manually, add these values by copying this and saving it as .reg file:
```
Windows Registry Editor Version 5.00

; Make all protocols available
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp\]
DefaultSecureProtocols=DWORD:0xAA0

; Make all protocols available
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp\]
DefaultSecureProtocols=DWORD:0xAA0

; TLS 1.1
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client]
DisabledByDefault=DWORD:0
Enabled=dword:1

; TLS 1.2
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
DisabledByDefault=DWORD:0
Enabled=dword:1
```

They should be added automatically by some .Net framework update, but in case the OS doesn't have them added already, you can put them manually, this will also improve compatibility with a lot of new .Net apps

# 8\) Packaging the App
To package the App we must use a compatible version of `pyinstaller` that works on Windows 7, according to: https://pypi.org/project/pyinstaller/ `pyinstaller` latest version should work in Windows 7, as stated by:
```
Windows (32bit/64bit/ARM64):
PyInstaller should work on Windows 7 or newer, but we only officially support Windows 8+.
```

~~However it clearly doesn't work, so maybe we can try using an older version, or opening an issue on their Repo.~~
EDIT: It may be because the project is targeting Python 3.11, i think that if you package it using Python 3.8 it will work

For now the solution would be to provide an unpackaged version of the App, and add a Batch script that just starts it, like this:
`"Launch.bat"`
```
@echo off
pushd %~dp0
python run.py
```

And maybe another script for installing the necessary requirements from requirements.txt
`"InstallReqs.bat"`
```
@echo off
pushd %~dp0
pip install -r requirements.txt
```

# Extra
We can add this to "run.py" to set a fixed width and height for all Windows users (helps Win 7 as the CMD size isn't remembered, and the width can't be changed by much without touching the CMD properties)
```
# Automatically increase the width and height of the CMD window (Windows only)
cmd = 'mode 120,40'
os.system(cmd)
```

**Comment by Arrowar** [comment]
Aggiunto tutto, ora dovrebbe andare anche la class my_request
