### ISSUE TITLE
Different season range

### ISSUE THREAD

**Issue by lucabrignani** [AstraeLabs/VibraVid#116]
When i try to download for example LOL CHI RIDE E' FUORI season 201 i can't. the program says 5 season(s) found, when i hit 5 it gives me an error
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/167694468/74741298-2adf-42ed-badf-80b06e611fe3)
but when i hit 201 it says
Done.

**Comment by Arrowar** [comment]
Ora dovrebbe andare: https://github.com/Ghost6446/StreamingCommunity_api/commit/651f8a7e3c42afb02d7076d61f5fbb13a4e6d5c4
