### ISSUE TITLE
Error while trying in a docker container

### ISSUE THREAD

**Issue by teocavaa** [AstraeLabs/VibraVid#119]
![Screenshot 2024-04-26 110622](https://github.com/Ghost6446/StreamingCommunity_api/assets/95353156/2f269a43-9bd2-4b91-b3a4-64b768b4ccae)
![Screenshot 2024-04-26 110635](https://github.com/Ghost6446/StreamingCommunity_api/assets/95353156/08006065-b83d-4112-866f-827493a06aa1)
I received this two error while trying to run the script in a docker container.

**Comment by Arrowar** [comment]
Are you sure that you are in the same folder where dockerfile are store ?

**Comment by teocavaa** [comment]
now it's work. Thanks for all
