### ISSUE TITLE
Error 409

### ISSUE THREAD

**Issue by Stefinho86** [AstraeLabs/VibraVid#12]
Scusami tanto: scaricato ex-novo, come da te detto, ultima release in oggetto, ma non scarica. Ti allego lo screen. 
Cosa posso fare?
![stream](https://github.com/Ghost6446/StreamingCommunity_api/assets/133981343/d194286a-2f11-4823-b997-801659d11b08)

**Comment by Arrowar** [comment]
![immagine_2024-01-08_173202168](https://github.com/Ghost6446/StreamingCommunity_api/assets/62809003/a7293bb5-5509-4b23-9f50-b92641850655)

Prova a rinominare la cartella principale togliendo "-" e "." vari

**Comment by Stefinho86** [comment]
Fatto, dà sempre lo stesso errore "ValueError: non-hexadecimal number found in fromhex() arg at position 0".

**Comment by Arrowar** [comment]
Riprova a scaricare ora, penso sia un problema solo del tuo pc, ho provato su altri e funziona perfettamente con lo stesso titolo.
