### ISSUE TITLE
macOS script stopped working [openssl error]

### ISSUE THREAD

**Issue by lorenzovadacca** [AstraeLabs/VibraVid#120]
Traceback (most recent call last):
  File "/Users/lorenzo/Documents/File/Progetti/Script/StreamingCommunity_api/run.py", line 12, in <module>
    from Src.Api import (
  File "/Users/lorenzo/Documents/File/Progetti/Script/StreamingCommunity_api/Src/Api/__init__.py", line 3, in <module>
    from .film import download_film
  File "/Users/lorenzo/Documents/File/Progetti/Script/StreamingCommunity_api/Src/Api/film.py", line 22, in <module>
    video_source = VideoSource()
                   ^^^^^^^^^^^^^
  File "/Users/lorenzo/Documents/File/Progetti/Script/StreamingCommunity_api/Src/Api/Class/Video.py", line 28, in __init__
    'user-agent': get_headers()
                  ^^^^^^^^^^^^^
  File "/Users/lorenzo/Documents/File/Progetti/Script/StreamingCommunity_api/Src/Util/headers.py", line 19, in get_headers
    random_headers = ua.get_random_user_agent("firefox")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lorenzo/Documents/File/Progetti/Script/StreamingCommunity_api/Src/Lib/UserAgent/user_agent.py", line 104, in get_random_user_agent
    return random.choice(browser_user_agents.get(browser.lower(), []))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/random.py", line 347, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

**Comment by Arrowar** [comment]
Se riesci vai in lib/user_agent, printa il path di user_agent.json e guarda se esiste, ma sicuramente no dato che non trova niente.

**Comment by lorenzovadacca** [comment]
Nel percorso
~/StreamingCommunity_api/Src/Lib/UserAgent
vedo solo:
__init__.py
__pycache__
user_agent.py

**Comment by Arrowar** [comment]
Controlla il file user_agent.py. Dovrei leggere il codice e trovare da quale parte path.

**Comment by lorenzovadacca** [comment]
￼

**Comment by Arrowar** [comment]
Appena arrivo a casa ti rispondo meglio

**Comment by Arrowar** [comment]
Prova a fare il print di questa variabile: https://github.com/Ghost6446/StreamingCommunity_api/blob/main/Src%2FLib%2FUserAgent%2Fuser_agent.py#L57 e controllare se il path esiste nel PC.

**Comment by lorenzovadacca** [comment]
Provo a fare print ma mi restituisce un errore identico.
Il file fake_user_agent.json non esiste nel pc.

**Comment by Arrowar** [comment]
E se fai solo il print di: tempfile.gettempdir(), forse tempfile non funziona per mac.

**Comment by lorenzovadacca** [comment]
Stesso errore

**Comment by Arrowar** [comment]
Prova a tornare qualche versione di python indietro, tipo la 3.10 o 3.9

**Comment by lorenzovadacca** [comment]
Restituisce altri errori di pacchetti incompatibili

**Comment by Arrowar** [comment]
Prova a disinstillare completamente python, creare un ambiene pulito, e provare ad eseguire solo tempfile.gettempdir(), con la versione 3.11, senza niente dopo aver disinstallato.

**Comment by lorenzovadacca** [comment]
Stesso errore, non so più cosa fareLorenzo VadaccaIl giorno 1 mag 2024, alle ore 15:54, Giova ***@***.***> ha scritto:﻿
Prova a disinstillare completamente python, creare un ambiene pulito, e provare ad eseguire solo tempfile.gettempdir(), con la versione 3.11, senza niente dopo aver disinstallato.

**Comment by Arrowar** [comment]
Strano, in che sistema sei ? 

Ma eseguento direttamente sul terminale: 
`
import tempfile; print(tempfile.gettempdir())
`
da errori ?

**Comment by lorenzovadacca** [comment]
Output:

/var/folders/4k/0jfxrb_512s98lfzhgxvj4m80000gn/T

Lorenzo Vadacca

> Il giorno 1 mag 2024, alle ore 16:44, Giova ***@***.***> ha scritto:
> 
> print(tempfile.gettempdir())

**Comment by Arrowar** [comment]
Teoricamente ora dovrebbe andare.

**Comment by lorenzovadacca** [comment]
Con Python 3.12 stesso erroreCon Python 3.9 altro errore Lorenzo VadaccaIl giorno 1 mag 2024, alle ore 16:34, Lorenzo Vadacca ***@***.***> ha scritto:﻿Stesso errore, non so più cosa fareLorenzo VadaccaIl giorno 1 mag 2024, alle ore 15:54, Giova ***@***.***> ha scritto:﻿
Prova a disinstillare completamente python, creare un ambiene pulito, e provare ad eseguire solo tempfile.gettempdir(), con la versione 3.11, senza niente dopo aver disinstallato.

**Comment by Arrowar** [comment]
Riesci ad incollare l'errore della 3.9 ?

**Comment by lorenzovadacca** [comment]
Lo screenshot è della 3.9Lorenzo VadaccaIl giorno 1 mag 2024, alle ore 17:44, Giova ***@***.***> ha scritto:﻿
Riesci ad incollare l'errore della 3.9 ?

**Comment by Arrowar** [comment]
Prova ad incollare nuovamente lo screen dato che github mi sa che non te l'ha accettato.

**Comment by Arrowar** [comment]
Se no caricato direttamente su discors sul canale issue.

**Comment by lorenzovadacca** [comment]
Postato su discordLorenzo VadaccaIl giorno 1 mag 2024, alle ore 18:48, Giova ***@***.***> ha scritto:﻿
Se no caricato direttamente su discors sul canale issue.
