### ISSUE TITLE
Audio out of sync

### ISSUE THREAD

**Issue by Pedruuxx** [AstraeLabs/VibraVid#121]
Buongiorno a tutti. Ho riscontrato un problema nella nuova serie Fallout (https://streamingcommunity.marketing/titles/7497-fallout). 
Quando provo a scaricare episodi, il primo viene scaricato correttamente. Il secondo episodio (https://streamingcommunity.marketing/watch/7497?e=59525), anche con il debug attivo, viene scaricato ma l'audio è completamente fuori-sincronizzazione. Ho provato a scaricarlo più volte e a riprodurlo con vari players (WMP, VLC, Film e TV di Microsoft). 
Non ho idea del motivo.

**Comment by Arrowar** [comment]
E gia presente un issue per lo stutter, per l'audio fuori sync, ti consiglio di abbase i worker a 5 sul file config.json, probabilemente ti hanno bloccato dal scaricarli tutti: https://github.com/Ghost6446/StreamingCommunity_api/issues/95
