### ISSUE TITLE
Caratteri non gestiti

### ISSUE THREAD

**Issue by a-maggioni** [AstraeLabs/VibraVid#126]
Ciao, segnalo alcuni caratteri che non vengono gestiti correttamente (→, ộ, ồ, ecc.).
Piuttosto che lanciare un'eccezione si può pensare di avere un carattere speciale da usare come fallback?

**Comment by Arrowar** [comment]
Il problema è trovare i caratteri speciali, esiste già la funzione unidecode, segnala sul canale discord quello che non vanno anche se per il momento neanche uno funziona.
