### ISSUE TITLE
HTTP Error 503 e durata video

### ISSUE THREAD

**Issue by a-maggioni** [AstraeLabs/VibraVid#127]
Ciao, nei log vedo questo errore:

`ERROR:root:Request failed for URL 'xxx': HTTP Error 503: Service Temporarily Unavailable`

Al termine del download il file scaricato risulta riproducibile, ma ha una durata nettamente inferiore al video originale (es. 20 minuti al posto di 60). Anche la durata indicata prima del download in alcuni casi risulta sbagliata.

**Comment by Arrowar** [comment]
Entra nel canale discord. è un problema del loro server.
