### ISSUE TITLE
Problema nello scaricamento

### ISSUE THREAD

**Issue by Marcoluca56** [AstraeLabs/VibraVid#128]
Ciao a tutti e innnanzitutto complimenti a Ghost6446 per il programma.
L'ho provato ma riscontro dei problemi in fase di scaricamento.
Nello specifico (per qualunque tipo di film o serie che vado a scaricare) mi dà sempre questi tipi di errori

![problema programma](https://github.com/Ghost6446/StreamingCommunity_api/assets/26649931/c6c2efb8-094e-48a5-b66b-d9c93859e7f5)

Il file viene scaricato alla fine, ma se la puntata è di 1 ora ad esempio, mi viene scaricata solo 10-15 minuti.
Come mai? Come posso risolvere?

Ho provato anche ad aumentare il tempo del timeout ma ricevo comunque questo tipo di errore:
![problerma programma 2](https://github.com/Ghost6446/StreamingCommunity_api/assets/26649931/d086b111-75b1-4220-91bb-18fe2b412f8a)

Grazie in anticipo

**Comment by Arrowar** [comment]
È un problema del loro server al momento, entra nel discorso per vedere la discussione.
