### ISSUE TITLE
Error 401.

### ISSUE THREAD

**Issue by iFedix** [AstraeLabs/VibraVid#129]
Ciao! Sto provando ad utilizzare il tuo script per Silicon Valley, però quando avvio il tool (tramite docker), ottengo questo:
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/23638108/5ff7bfb8-fdb3-44b0-96ee-39334c4af9ad)
Qualche idea su come risolvere? Grazie!

**Comment by Arrowar** [comment]
Oggi faccio delle prove e ti dico.

**Comment by iFedix** [comment]
Giusto per completezza ho provato anche la versione non Docker avviata su Pycharm. Stesso identico problema e per qualunque serie che ho provato

**Comment by Arrowar** [comment]
Si si il problema è che stanno cambiano la gestione.
