### ISSUE TITLE
Wrong m3u8 url

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#13]
...
30 -> Unbelievable - tv
31 -> Charlie Says - movie
32 -> La nave matta di Mister Roberts - movie

Index to download: : 0

Movie select: Merry Christmas
[23:07:34] Wrong m3u8 url                                                                                     m3u8.py:96

**Comment by Arrowar** [comment]
Try to retry after few second

**Comment by ludogemma** [comment]
no nemmeno il giorno dopo

p.s. scusa se appare il log in inglese, ma è perchè ce l'ho impostato su win così (per scelta ovviamente) :)

**Comment by ludogemma** [comment]
usando l'altra tua versione scraper mettendo ID funziona, sarebbe ottimo se tu aggiungessi la possibilità in questo di eventualmente scegliere l'ID del video così da evitare con alcuni titoli questo problema.

grazie mille per i tuoi scripts :)

**Comment by Arrowar** [comment]
Oggi provo a vedere di risolvere

**Comment by Arrowar** [comment]
Ora va

**Comment by ludogemma** [comment]
che intendi con ora va? hai fatto una nuova versione?

**Comment by Arrowar** [comment]
Si 1h fa.

**Comment by ludogemma** [comment]
si ho appena scaricato la nuova versione, grazie :)
una delucidazione, lo script sceglie sempre la max qualità possibile di default vero?

**Comment by Arrowar** [comment]
Si
