### ISSUE TITLE
Download Ep Anime Series error name

### ISSUE THREAD

**Issue by Demential98** [AstraeLabs/VibraVid#130]
While downloading anime series exists an error that downloads you 2 times ep_1 
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/92541225/56cdeb67-a4da-4d2c-85e3-57ab2f497506)
this is not a problem when downloading but if and error occurs with the download it will not redownload ep 2

**Comment by Arrowar** [comment]
You insert * or [] or a number ?

**Comment by Demential98** [comment]
At first I insert *, when it failed the download I've inserted only 2, it started downloading third ep 
possiamo anche parlare in italiano o sentirci su discord

**Comment by Arrowar** [comment]
Si scrivi su issue su discord, qualcuno aveva già scritto per gli episodi. Comunque aggiunge anche te l'errore e in quali circostanze.
