### ISSUE TITLE
Nome del file errato

### ISSUE THREAD

**Issue by andrea-ble** [AstraeLabs/VibraVid#131]
Ciao,
il nome del file del singolo episodio di una serie ha il # stagione uguale al # numero episodio!
Es:
Season 2
xx-s01e01
xx-s02e02
xx-s03e03
xx-s04e04
Ciao

**Comment by Ghost6446** [comment]
Ciao riusciresti a fare un fork e risolverlo. Grazie

**Comment by Arrowar** [comment]
> Ciao, il nome del file del singolo episodio di una serie ha il # stagione uguale al # numero episodio! Es: Season 2 xx-s01e01 xx-s02e02 xx-s03e03 xx-s04e04 Ciao

Risolto
