### ISSUE TITLE
how to change output filename, resolution etc

### ISSUE THREAD

**Issue by alessiozanutta** [AstraeLabs/VibraVid#137]
there's no info on how to change filename of the output file
i got always just 1.mp4, 2.mp4 etc..
where should I act to change?
this is valid also for resolution etc

**Comment by Arrowar** [comment]
In che sito ?

**Comment by alessiozanutta** [comment]
animeunity
<img width="169" alt="image" src="https://github.com/Ghost6446/StreamingCommunity_api/assets/70146247/fdd657a6-739e-4d8f-9278-e71c3ccff0b9">

**Comment by Arrowar** [comment]
Il problema è che ogni episodio di animeunity ha come nome 1 2 3 ..., non esiste il nome. Se hai una soluzione scrivi pure su discord.
