### ISSUE TITLE
some files not downloaded completely

### ISSUE THREAD

**Issue by alessiozanutta** [AstraeLabs/VibraVid#138]
some files, such as MOB PSYCHO S1E6, are not downloaded completely from animeunity
some minutes at the end are always missing wrt the video streamed in the website
keeps occurring after redownload.

**Comment by alessiozanutta** [comment]
<img width="1138" alt="image" src="https://github.com/Ghost6446/StreamingCommunity_api/assets/70146247/bb292958-bb60-4d2a-a8c9-d5f985c888ca">

**Comment by Arrowar** [comment]
Prova ad abilitate use_codec

**Comment by Arrowar** [comment]
Aggiunto commit per risolvere.
