### ISSUE TITLE
can't download tv series

### ISSUE THREAD

**Issue by jacopeste05** [AstraeLabs/VibraVid#14]
Traceback (most recent call last):
  File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\run.py", line 42, in <module>
    main()
  File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\run.py", line 37, in main
    download_tv(db_title[index_select]['id'], db_title[index_select]['name'].replace(" ", "+"), site_version, domain)
  File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\Src\Api\tv.py", line 106, in main_dw_tv
    console.print(f"[blue]Season find: [red]{get_info_tv(tv_id, tv_name, version, domain)}")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\Src\Api\tv.py", line 26, in get_info_tv
    if req.ok():
       ^^^^^^^^
TypeError: 'bool' object is not callable

**Comment by Arrowar** [comment]
Oggi risolvo

**Comment by Arrowar** [comment]
> Traceback (most recent call last): File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\run.py", line 42, in main() File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\run.py", line 37, in main download_tv(db_title[index_select]['id'], db_title[index_select]['name'].replace(" ", "+"), site_version, domain) File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\Src\Api\tv.py", line 106, in main_dw_tv console.print(f"[blue]Season find: [red]{get_info_tv(tv_id, tv_name, version, domain)}") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\Src\Api\tv.py", line 26, in get_info_tv if req.ok(): ^^^^^^^^ TypeError: 'bool' object is not callable

Ora funziona con la nuova versione

**Comment by Ghost6446** [comment]
Riesci a darmi il nome della serie ?

**Comment by dizplayy** [comment]
Certo! 
166 - percy jackson e gli dei dell'olimpo
