### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by scaistar** [AstraeLabs/VibraVid#141]
Che succede?
non scarica più nulla. dà sempre questo errore

ERROR:root:Request failed for URL 'https://162.19.254.232/hls/200/b/a0/ba02c274-3fdb-474a-9477-581ee987dd8f/video/1080p/0050-1250.ts?token=PFK2hEq5jDJZy7Ad4unHAA&expires=1722940852': {'error_code': '403', 'message': 'Forbidden'}
=>  HTTP Error 403: Forbidden

**Comment by Arrowar** [comment]
Prova con l'ultimo commit che non usa gli IP.

**Comment by scaistar** [comment]
fatto. ma adesso mentre sta eseguendo il download si interrompe improvvisamente con una serie di errori
ERROR:root:Request-related exception while downloading segment: 503 Server Error: Service Temporarily Unavailable for url: https://******.scws-content.net/hls/140/4/48/4483c4f2-f365-4629-ad41-46f207c7531e/video/1080p/0497-0750.ts?token=7UaFadESez7UhScwml66cQ&expires=1723043782
e i segmenti si fermano intorno al 42%

**Comment by scaistar** [comment]
comunque ho provato a scaricare una puntata di SThings con app LJDownloader e succede lo stesso. :( Arrivato a 18% si è fermato con errore code 502. Request_not_successful.. url...

**Comment by Arrowar** [comment]
Scrivi sul discord, quando riesco porto l'update.
