### ISSUE TITLE
Errore 503

### ISSUE THREAD

**Issue by iTzPinGuu** [AstraeLabs/VibraVid#145]
Ciao, molto spesso mi da errore 503 quando provo a scaricare da Streamingcommunity (ad esempio Camera Cafè) 
`ERROR:root:Request-related exception while downloading segment: 503 Server Error:`

Premetto che ho scaricato anche altro e funzionava, quindi ho tutti i pacchetti necessari come ffmpeg ecc..

**Comment by Arrowar** [comment]
Si si certo, per scaricare ancora dovresti settare j workers a 2 o 1 oppure comprarti dei proxy anonimi e scaricare da lì.
