### ISSUE TITLE
Little initial issue

### ISSUE THREAD

**Issue by Topicform** [AstraeLabs/VibraVid#155]
Good morning and thanks for the Script.
I'm at the beginning and I don't know how to continue.
The script starts regularly and I find this writing... Insert category (): (0): I made several attempts but to no avail. thanks for your attention and good work :)

**Comment by Arrowar** [comment]
Che errori da prima, solitamente se non trova niente manca qualche libreria da installare. Hai fatto pip install -r requirements.txt, come scritto sulla guida del readme.

**Comment by Topicform** [comment]
Buongiorno Lovi e grazie per avermi risposto. A dire il vero ho omesso Openssl. Pycryptodome é installato. Può essere che Openssl sia il problema?

**Comment by Arrowar** [comment]
Prova a installare openssl e disinstallare pycryptodome.

**Comment by Arrowar** [comment]
> Buongiorno Lovi e grazie per avermi risposto. A dire il vero ho omesso Openssl. Pycryptodome é installato. Può essere che Openssl sia il problema? 

Se riesci anche uno screen del terminale.

**Comment by Arrowar** [comment]
> Buongiorno Lovi e grazie per avermi risposto. A dire il vero ho omesso Openssl. Pycryptodome é installato. Può essere che Openssl sia il problema?

Se riprovi ora dovrebbe andare

**Comment by Topicform** [comment]
Buongiorno e grazie per l'impegno... nel pomeriggio controllo e le faccio sapere.

**Comment by Arrowar** [comment]
> Buongiorno e grazie per l'impegno... nel pomeriggio controllo e le faccio sapere. 

Grazie mille allora aspetto notizie.
