### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by Topicform** [AstraeLabs/VibraVid#156]
![-6041885509699093997_121](https://github.com/Lovi-0/StreamingCommunity/assets/31699241/a888e5ef-7438-4ab9-a94c-31ac952fe7f4)

**Comment by Topicform** [comment]
Nello screen mi dice di utilizzare una delle opzioni disponibili... e qui mi fermo :(

**Comment by Topicform** [comment]
Non riesco ad inserire nessuna scelta... Grazie :)

**Comment by k133** [comment]
Ti mancano le librerie Python.
Digita nel prompt dei comandi: pip install -r requirements.txt

**Comment by Arrowar** [comment]
> Non riesco ad inserire nessuna scelta... Grazie :)
> 

Usa la versione di ieri sera.

**Comment by Topicform** [comment]
La versione di ieri sera è l'unica che sto usando e le librerie sono installate come da comando... Ricontrollo Lovi e ti faccio sapere. Grazie e scusami.

**Comment by Arrowar** [comment]
Prova a fare pip install della libreria che da errore però. Oppure cancellare python e reinstallare tutto con i requirements.

**Comment by k133** [comment]
prova nel prompt con:
pip3 install qbittorrent-api
pip3 install python-qbittorrent

**Comment by Topicform** [comment]
Ti faccio sapere👍

**Comment by Arrowar** [comment]
> ![-6041885509699093997_121](https://private-user-images.githubusercontent.com/31699241/343077682-a888e5ef-7438-4ab9-a94c-31ac952fe7f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzI1NzUsIm5iZiI6MTcxOTQ3MjI3NSwicGF0aCI6Ii8zMTY5OTI0MS8zNDMwNzc2ODItYTg4OGU1ZWYtNzQzOC00YWI5LWE5NGMtMzFhYzk1MmZlN2Y0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA3MTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwY2Q5ZjNjZGNhNmJhMWNjNGVkNmY5ZjU4ZTUxYWI5Y2I3MDE1NWFmNGM3YmIyMWZiNTMzOWIxZjJiODI1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xgSE8Jo7Gv18TIl2lZF-T6cvj0XIdhttt1AXr61PqdE)

Sei riuscito a risolvere ?

**Comment by Topicform** [comment]
Rientro domani per lavoro poi ti dico... Questo tuo link non si apre... https://private-user-images.githubusercontent.com/31699241/343077682-a888e5ef-7438-4ab9-a94c-31ac952fe7f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzI1NzUsIm5iZiI6MTcxOTQ3MjI3NSwicGF0aCI6Ii8zMTY5OTI0MS8zNDMwNzc2ODItYTg4OGU1ZWYtNzQzOC00YWI5LWE5NGMtMzFhYzk1MmZlN2Y0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA3MTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwY2Q5ZjNjZGNhNmJhMWNjNGVkNmY5ZjU4ZTUxYWI5Y2I3MDE1NWFmNGM3YmIyMWZiNTMzOWIxZjJiODI1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xgSE8Jo7Gv18TIl2lZF-T6cvj0XIdhttt1AXr61PqdE

**Comment by Topicform** [comment]
BINGO amico: Ho seguito il tuo prezioso consiglio installando pip3 install qbittorrent-api
pip3 install python-qbittorrent...Anche se è un termine abusato, Grazie di cuore:)

**Comment by Topicform** [comment]
Ciao e scusa se mi permetto, è possibile inserire anche la ricerca bel CB01? grazie e complimenti per lo splendido script.

**Comment by Topicform** [comment]
Ciao e scusa se mi permetto, è possibile inserire anche la ricerca per CB01? grazie e complimenti per lo splendido script.

**Comment by Arrowar** [comment]
> Ciao e scusa se mi permetto, è possibile inserire anche la ricerca per CB01? grazie e complimenti per lo splendido script.

È già nella lista delle cose da fare ma non ho molto tempo per aggiungerli.

**Comment by Topicform** [comment]
Molto bene, prenditi il tempo che vuoi. Grazie 1000.
