### ISSUE TITLE
ALTA DEFINIZIONE - SSL FAILED + FIND DOMAIN

### ISSUE THREAD

**Issue by k133** [AstraeLabs/VibraVid#158]
Ciao Lovi-0, ti allego lo screenshot che riporta i due errori:

- SSL: CERTIFICATE_VERIFY_FAILED
- ERROR:root:Failed to find a new domain for: https://altadefinizione

Ti preciso che il dominio https://altadefinizione.vodka era, ed è, online
 
![altadefinizione](https://github.com/Lovi-0/StreamingCommunity/assets/50711484/d82f11bb-3cf1-44a8-bd99-df9faff70f94)

**Comment by Arrowar** [comment]
Se cambi sul config il dominio in vodka funziona ?

**Comment by k133** [comment]
> Se cambi sul config il dominio in vodka funziona ?

Strano, non ho toccato nulla e ora lo script funziona correttamente... 
Se si dovesse ripresentare, farò la modifica che mi hai suggerito. Per il momento ti ringrazio per la celere risposta. Ciao

**Comment by Arrowar** [comment]
Di niente si alcune volte ha ancora dei problemi se i timeout sono troppi veloci
