### ISSUE TITLE
Error 409

### ISSUE THREAD

**Issue by greyhat94** [AstraeLabs/VibraVid#16]
I have installed all the requirements, as well as updated the required module. However, when I tried to run the software, it appears this on my prompt: 

```
C:\Users\umile\Desktop\StreamingCommunity_api>python run.py
[01:05:01] UPDATE DOMANIN                                                                                     page.py:24

C:\Users\umile\Desktop\StreamingCommunity_api>
```

How can I fix this? I rely on your help and look forward to hearing from you sooner.

**Comment by Arrowar** [comment]
I will upload to new domain today.
