### ISSUE TITLE
Failed auto update domain. (how to solve)

### ISSUE THREAD

**Issue by manuel09** [AstraeLabs/VibraVid#160]
streamingcommunity gives an error if you try to search and returns the old url

**Comment by Arrowar** [comment]
Try add screenshot of the error.

**Comment by manuel09** [comment]
![Cattura](https://github.com/user-attachments/assets/edf4a8eb-720c-4f5c-b759-7cc6d276a644)

**Comment by Arrowar** [comment]
Try verify is .boston is the real domain or not and if they change location of version. 

Or just retry.

**Comment by manuel09** [comment]
no what appears is the old domain, they changed it and the script obviously gives an error

**Comment by manuel09** [comment]
![Cat](https://github.com/user-attachments/assets/4686a3c8-42cb-4506-a0e6-df1f9b5b93c3)

this is the new one

**Comment by Arrowar** [comment]
Si può succedere che dia il vecchio, per il momento cambialo sul file di config.json e dovrebbe andare

**Comment by manuel09** [comment]
perfetto ha funzionato , comunque simpatico prima in inglese e poi in italiano hahah

**Comment by Arrowar** [comment]
Piccolo switch hahaha, ho letto il terminale in italiano.
