### ISSUE TITLE
Can you add streaming with VLC android/windows app and retrieving the new link from a google search?

### ISSUE THREAD

**Issue by EspWifi8266** [AstraeLabs/VibraVid#161]
I have already tried to add this feature and if added correctly I have seen that it works great and VLC plays the video or episode correctly both on the phone and on Windows. This feature would be very useful especially if the program is run on a firestick or android box for TV!

**Comment by EspWifi8266** [comment]
And then I don't know if it's a bad idea but it could be useful to get the new link of the sites by scraping a Google search, I tried it some time ago with PHP not python but it worked well.

**Comment by Arrowar** [comment]
I can't add it at the moment, I don't have much time to keep up with the project.

If you want, try writing the code to update the repo yourself, also the main purpose was to download and then use vlc to play it.

**Comment by EspWifi8266** [comment]
Ok even if I just started I will try to carry on with the project, the idea and the project is well structured and extracts the video link correctly so with VLC on a Fire Stick you can easily play the video without downloading anything.

**Comment by Arrowar** [comment]
> Ok even if I just started I will try to carry on with the project, the idea and the project is well structured and extracts the video link correctly so with VLC on a Fire Stick you can easily play the video without downloading anything.

Yes with m3u8 is a lot simple.

**Comment by EspWifi8266** [comment]
I wanted to ask you if you will continue the project or not. Anyway I want to congratulate you for the project you did, you did it really well, then for now I added a function that automatically updates in the config.json file all domains by searching for them on Google and checking them (if they are valid and if there is a 403 status save the redirect domain this works well for streaming community) if it can be useful to you I can share it with you.

**Comment by Arrowar** [comment]
yes the redirect search was something i wanted to do, i think i'll keep the project but as i've already told others, i'm finishing building the pc and as always there are some unforeseen events (i have to fix gpu). So if all goes well and the parts arrive by october i should be back up and running.

**Comment by Arrowar** [comment]
Inoltre c'erano delle altre cose da aggiungere che per il momento sono nel backup in attesa che arrivino tutti i pezzi.

**Comment by EspWifi8266** [comment]
Ok , per curiosità quali funzioni? Ah comunque la funzione per cercare i domini aggiornati su Google la dovrei aver finita l'ho testata per un bel po' di volte e sono sicuro che funzioni bene anche perché oltre a controllare lo stato ho fatto in modo che il link trovato da Google sia sicuramente della piattaforma giusta.

**Comment by Arrowar** [comment]
Okay perfetto, funzionalità di ottimizzazione  della velocità anche se dovremmo esserci e degli altri controllo per evitare problemi con i: ":;'- anche se teoricamente dovrebbero andare.

**Comment by EspWifi8266** [comment]
Poi non so se ti interessa ma per me (che lo uso su una firestick) può essere una buona idea anche aggiungere una funzione per cercare i film del momento o cercare i film per genere per scoprire film nuovi, per il momento ho scritto un semplice plug in che lo fa usando TMDb che funziona bene ed è facile da implementare se vuoi quando potrai ti posso condividere volentieri anche quello

**Comment by Arrowar** [comment]
Si certo l'avevo aggiunto tempo fa anche per streaming comunity ma dopo l'avevo rimosso dato che non riuscivo a finirlo, ma penso che sia un'ottima cosa da aggiungere magari all'inizio per film e serie del momento. Il problema era trovare un'api o un sito abbastanza statico per fare il tutto

**Comment by EspWifi8266** [comment]
Non va bene usare un sito come TMDb? Il sito per quel poco che ho visto ha un API gratuita che dovrebbe essere semplice da usare può essere un idea, ho già provato a fare un plug-in e funziona bene per quel che ho visto se ti interessa il link è: https://www.themoviedb.org/

**Comment by Arrowar** [comment]
Si va più che bene se ha anche l'api ancora meglio

**Comment by EspWifi8266** [comment]
![Screenshot_20240822-145425](https://github.com/user-attachments/assets/a19d7c14-6fd2-4cfb-8da7-20c500c3cf01)
si la cosa buona è che l'API è gratuita e a quanto pare non ha limiti di richieste anche se serve un API Key, per essere in regola vogliono solo che tu gli dia i crediti

**Comment by Arrowar** [comment]
Nessun problema allora

**Comment by Arrowar** [comment]
> 
> ![Screenshot_20240822-145425](https://github.com/user-attachments/assets/a19d7c14-6fd2-4cfb-8da7-20c500c3cf01)
> si la cosa buona è che l'API è gratuita e a quanto pare non ha limiti di richieste anche se serve un API Key, per essere in regola vogliono solo che tu gli dia i crediti

Molto bello se hai voglia passami pure il codice su discord

**Comment by EspWifi8266** [comment]
Va bene

**Comment by EspWifi8266** [comment]
Come ti posso trovare su discord? Ti ho trovato su YouTube ma non hai nessun contratto...

**Comment by EspWifi8266** [comment]
Poi a me dà errore quando tenta di trovare il nuovo dominio con il tuo metodo ti consiglio di usare Google come ho fatto io credo sia meglio forse:
![Screenshot_20240823-123557](https://github.com/user-attachments/assets/09e678af-6ac1-4018-94de-e925695edeca)

**Comment by Arrowar** [comment]
> Come ti posso trovare su discord? Ti ho trovato su YouTube ma non hai nessun contratto...

C'è il link sul readme

**Comment by Arrowar** [comment]
> Poi a me dà errore quando tenta di trovare il nuovo dominio con il tuo metodo ti consiglio di usare Google come ho fatto io credo sia meglio forse:
> ![Screenshot_20240823-123557](https://github.com/user-attachments/assets/09e678af-6ac1-4018-94de-e925695edeca)
> 
> 


Si probabilmente si se riesci passami il codice

**Comment by Arrowar** [comment]
I messaggi che hai scritto sul discord gli hai eliminati ?

**Comment by EspWifi8266** [comment]
Ti chiedo scusa sono minore ne ho parlato con i miei genitori e mi hanno negato di farlo perché hanno paura di eventuali multe, perciò ho eliminato tutti i file da discord

**Comment by Arrowar** [comment]
Nessun problema
