### ISSUE TITLE
Bug/Crash con i caratteri speciali

### ISSUE THREAD

**Issue by Marcoluca56** [AstraeLabs/VibraVid#162]
Ciao a tutti e complimenti innanzitutto per lo script.
Tuttavia ho notato che il programma ha qualche bug quando si prova a scaricare dei film con caratteri speciali come ad esempio "Alien: romulus"
avendo i due punti fa andare in crash lo script.
![problema](https://github.com/user-attachments/assets/76ae1de3-2845-4635-b547-fbe1d9847b1f)

**Comment by EspWifi8266** [comment]
Forse perché ci sono i due punti... Probabilmente si risolve semplicemente rimuovendo i caratteri speciali credo, provo a vedere se riesco a risolvere il problema

**Comment by Arrowar** [comment]
> Forse perché ci sono i due punti... Probabilmente si risolve semplicemente rimuovendo i caratteri speciali credo, provo a vedere se riesco a risolvere il problema

Va bene grazie mille anche se mi sembra strano con ":" si rompa tutto.

**Comment by EspWifi8266** [comment]
Per curiosità ho provato a creare un file contenente i : punti e il file manager del telefono dà errore quindi deduco che sia quello il problema, per il momento io non ho molto tempo per risolvere il problema... Però prima o poi ci proverò 😅

**Comment by EspWifi8266** [comment]
Ho risolto il problema basta aggiungere `file_path = re.sub(r'[<>:"/\\|?*]', '', file_path)` nella funzione `def can_create_file(file_path):' nel file os.py nella cartella util in Src

**Comment by Marcoluca56** [comment]
> Ho risolto il problema basta aggiungere `file_path = re.sub(r'[<>:"/\\|?*]', '', file_path)` nella funzione `def can_create_file(file_path):' nel file os.py nella cartella util in Src

Esattamente in quale riga? Perchè ho provato ad aggiungerlo ma non risolve il problema

**Comment by EspWifi8266** [comment]
In fondo al file os.py ho modificato la funzione così e a me ha risposto il problema:
`
def can_create_file(file_path):


    file_path = re.sub(r'[<>:"/\\|?*]', '', file_path)
    """
    Checks if a file can be created at the given file path.

    Parameters:
        - file_path (str): The path where the file is to be created.

    Returns:
        bool: True if the file can be created, False otherwise.
    """
    current_system = platform.system()
    
    if not is_valid_filename(os.path.basename(file_path), current_system):
        return False

    try:
        with open(file_path, 'w') as file:

            pass
        
        os.remove(file_path)  # Cleanup if the file was created
        return True
    
    except OSError as e:
        if e.errno in (errno.EACCES, errno.ENOENT, errno.EEXIST, errno.ENOTDIR):
            return False
        raise  
`

**Comment by EspWifi8266** [comment]
Dimmi se anche a te risolve il problema comunque la funzione si trova alla riga 532 e quella parte di codice per sistemare la directory l'ho messa subito dentro la funzione

**Comment by Marcoluca56** [comment]
Ho provato ma l'errore a me rimane:


" File "<frozen os>", line 225, in makedirs
NotADirectoryError: [WinError 267] Nome di directory non valido: 'Video\\altadefinizione\\Movie\\Alien: Romulus'"

**Comment by EspWifi8266** [comment]
Strano... Io sono su termux magari cambia qualcosa... Ti dà solo questo errore o c'è qualche altra informazione che può essere utile? E poi che piattaforma hai scelto sempre altadefinizione?

**Comment by Arrowar** [comment]
Si teoricamente dovrebbe essere quella la funzione che si rompe

**Comment by Arrowar** [comment]
@Marcoluca56 teoricamente ora dovrebbe andare prova a controllare

**Comment by Marcoluca56** [comment]
> Strano... Io sono su termux magari cambia qualcosa... Ti dà solo questo errore o c'è qualche altra informazione che può essere utile? E poi che piattaforma hai scelto sempre altadefinizione?

Allego screen post aggiunta del codice, come vedi rimane sempre l'errore
<img width="636" alt="screen2" src="https://github.com/user-attachments/assets/7c58a81f-dcdb-413a-937c-c35cf5c9b558">
![screen](https://github.com/user-attachments/assets/a865f833-1b33-4865-99ba-f4169c55d1b9)

**Comment by Arrowar** [comment]
Si certo ho fatto un commit diverso 2 minuti fa risolvendo l'errore in modo diverso

**Comment by Marcoluca56** [comment]
> Si certo ho fatto un commit diverso 2 minuti fa risolvendo l'errore in modo diverso

Perfetto! Adesso funziona con la nuova versione. Grazie :)

**Comment by Arrowar** [comment]
Di niente
