### ISSUE TITLE
RISULTATI incompleti dopo la ricerca

### ISSUE THREAD

**Issue by scaistar** [AstraeLabs/VibraVid#163]
L'elenco dei risultati dopo aver selezionato una stagione di una serie TV risulta troncato a 10.

Me ne sono accorto perchè dopo aver iniziato la 5a stagione di SuperStore.. ho notato un "leggero" buco temporale nei fatti :)
Sono andato a controllare.. sul sito le puntate della Season4 sono 22 ma quando li ho cercati nell' elenco ne apparivano soltanto 10.

C'è da dire che cmq indicando il numero tra parentesi ad es. [11-22] riesco cmq a scaricarle anche senza visualizzarle in elenco

**Comment by Arrowar** [comment]
È scritto premere invio per vedere il resto della lista.

**Comment by scaistar** [comment]
beh.. veramente è "ENTER to restart". forse bisogna rivedere la traduzione ;)
è cmq c'è qualcosa che non va. Premendo ENTER, dopo la prima decina, vedo la seconda decina, e poi basta. insomma si perde cmq gli episodi 21 e 22
![rest2](https://github.com/user-attachments/assets/931bdaf4-7167-4f70-9b1a-d3386c7f505b)

**Comment by Arrowar** [comment]
Si probabilmente ho fatto qualche errore hahaha, mese prossimo riguardo

**Comment by Arrowar** [comment]
Ora dovrebbe essere risolto.
