### ISSUE TITLE
status error: 'int' object is not subscriptable.

### ISSUE THREAD

**Issue by tgiachi** [AstraeLabs/VibraVid#165]
Ciao!,
Quando cerco di un episodio di una  serie mi da questo errore (su `guardaserie` )

![image](https://github.com/user-attachments/assets/f033e333-bf9a-418a-8e5f-d5f4d96e735f)

Grazie!

**Comment by Arrowar** [comment]
> Ciao!,
> Quando cerco di un episodio di una  serie mi da questo errore (su `guardaserie` )
> 
> ![image](https://github.com/user-attachments/assets/f033e333-bf9a-418a-8e5f-d5f4d96e735f)
> 
> Grazie!
> 

Prova a diminuire i workers sul file di config.

**Comment by tgiachi** [comment]
Perfetto e grazie!

**Comment by Arrowar** [comment]
Di niente
