### ISSUE TITLE
errore con nuova versione scaricata

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#166]
C:\Users\ludo\Desktop\StreamingCommunity2v>python run.py
Traceback (most recent call last):
  File "C:\Users\ludo\Desktop\StreamingCommunity2v\run.py", line 20, in <module>
    from Src.Lib.TMBD.tmbd import tmdb
ModuleNotFoundError: No module named 'Src.Lib.TMBD'

inoltre volevo fare presente che non esiste nel pacchetto che scarichi il file update_version.py... quinid non si può fare l'update direttamente..

**Comment by Arrowar** [comment]
Prova a riscaricare mi sembra strano che non ti trovi la libreria.

**Comment by Arrowar** [comment]
Update version funziona solo con una nuova versione non quando faccio un commit. Però appena ho modo faccio una nuova versione.

**Comment by ludogemma** [comment]
l'ultima versione non funziona invece prendendo la master adesso funziona, grazie

**Comment by Arrowar** [comment]
Di niente per il momento il master funziona.
