### ISSUE TITLE
Subtitle info

### ISSUE THREAD

**Issue by Simoneu01** [AstraeLabs/VibraVid#168]
Ciao!

é possibile aggiungere nella creazione del media con FFMPEG la lingua della traccia dei sottotitoli scaricata così che rimanga come metadato nel file?

**Comment by Arrowar** [comment]
Rimango disponibile già all'interno del file mp4 scaricato. Se lo apri con VLC e vai su seleziona lingua trovi tutte quelle scaricate.

**Comment by Simoneu01** [comment]
Ok, ho visto che ora con alcune serie lo fa. Con la serie Silicon valley tramite streamingcommunity non mi ha messo nessun nome ai file.
![image](https://github.com/user-attachments/assets/60dd7caa-2d24-479e-8cf5-7a1e074a4470)
![image](https://github.com/user-attachments/assets/4c196021-6388-4811-bfb7-1ac0651c8f59)

**Comment by Arrowar** [comment]
Appena ho tempo guardo anche se fino a 2 mesi fa funzionava.

**Comment by Arrowar** [comment]
> Ok, ho visto che ora con alcune serie lo fa. Con la serie Silicon valley tramite streamingcommunity non mi ha messo nessun nome ai file. ![image](https://private-user-images.githubusercontent.com/43807696/368300153-60dd7caa-2d24-479e-8cf5-7a1e074a4470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTUyMTEsIm5iZiI6MTcyNjgxNDkxMSwicGF0aCI6Ii80MzgwNzY5Ni8zNjgzMDAxNTMtNjBkZDdjYWEtMmQyNC00NzllLThjZjUtN2ExZTA3NGE0NDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA2NDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZDJjNTQ3MjE3ZWExZmIxNjhhMjlmYjU5ZDUzNWU1NGRjOWM0YWFmYjIzMGQ0YjJlMGYzMzcyNWQ5NDcyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G5IeB_4U0FIWTkS0qV1xEIMFHw9sAFJXsPqsNQz2x5Q) ![image](https://private-user-images.githubusercontent.com/43807696/368300332-4c196021-6388-4811-bfb7-1ac0651c8f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTUyMTEsIm5iZiI6MTcyNjgxNDkxMSwicGF0aCI6Ii80MzgwNzY5Ni8zNjgzMDAzMzItNGMxOTYwMjEtNjM4OC00ODExLWJmYjctMWFjMDY1MWM4ZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA2NDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkODRiNjM0MmY0MWIxNTUxOWUxMzg2NjI0ODNlNjNlYzQwNTdmYjNkM2Y5NDY5YWM2ZjBhODQzODIzNTMyNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g87forC8xZ7xi-PrrSf0qQrXGK0pWn8WYwRVr0Ai5Sk)

Per l'audio o visto che non si può fare niente dato che è singolo e non ci sono informazioni nella playlist invece per il subtitle appena riesco porto il fix.
