### ISSUE TITLE
Playlist m3u8 to download is empty

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#173]
Ciao perchè a volte, pur essendoci il film sul sito, da questo errore?

ERROR:root:Test request to https://vixcloud.co/playlist/265244?token=7387fc2b9677afa1f21c828000e4caf8&expires=1734186399&h=1 failed with error: Client error '401 Unauthorized' for url 'https://vixcloud.co/playlist/265244?token=7387fc2b9677afa1f21c828000e4caf8&expires=1734186399&h=1'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
[16:26:39] Playlist m3u8 to download is empty.

e poi un suggerimento, sarebbe bello se si potesse una volta cercato qualcosa, potere tornare indietro invece di dovere fare q e chiudere e di nuovo riaprire. insomma un qualcosa tipo per tornare indietro.

**Comment by Arrowar** [comment]
Per il primo problema dipende dal sito, invece per il secondo appena ho tempo lo faccio.

**Comment by Arrowar** [comment]
Aggiunto

**Comment by ludogemma** [comment]
ma funziona se faccio update?

**Comment by Arrowar** [comment]
No update funziona solo quando esce una nuova versione, non per singoli commit
