### ISSUE TITLE
Errore nell'installazione win-installer: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by TechDevOfficial** [AstraeLabs/VibraVid#174]
Script starting...
Checking if Chocolatey is installed...
Chocolatey is already installed. Skipping installation.
Checking if Python is installed...
Python is already installed. Skipping installation.
Checking if OpenSSL is installed...
OpenSSL is already installed. Skipping installation.
Checking if FFmpeg is installed...
FFmpeg is already installed. Skipping installation.
Checking if the .venv virtual environment already exists...
The .venv virtual environment already exists. Skipping creation.
Installing requirements...
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by TechDevOfficial** [comment]
![image](https://github.com/user-attachments/assets/ec404545-1144-496e-af70-43dd7fcce064)

**Comment by Arrowar** [comment]
Pip install -r requirements.txt, dentro la cartella
