### ISSUE TITLE
problema con 1337xx

### ISSUE THREAD

**Issue by jacopeste05** [AstraeLabs/VibraVid#176]
https://github.com/user-attachments/assets/ad8749b4-c188-44ee-889b-0620de6878f6
il sito 1337xx.to me lo apre usando qualsiasi browser, l'ho cambiato nel file config ma continua a darmi problemi e a consigliarmi siti che sono delle copie di 1337xx e sono fake

**Comment by Arrowar** [comment]
Sicuro che https://www.1337xx.to/ non funzioni ?

**Comment by jacopeste05** [comment]
https://github.com/user-attachments/assets/dc4ac2c7-f3c2-45da-81b7-1c194b3e7cec

**Comment by Arrowar** [comment]
Appena aggiunto il fix
