### ISSUE TITLE
Domanda su API

### ISSUE THREAD

**Issue by giusedm** [AstraeLabs/VibraVid#179]
Volevo chiedere se fosse possibile usare le Api per ricevere direttamente i link .m3u8 senza dover scaricare i video

**Comment by Arrowar** [comment]
> Volevo chiedere se fosse possibile usare le Api per ricevere direttamente i link .m3u8 senza dover scaricare i video

Si certo

**Comment by giusedm** [comment]
come?

**Comment by Arrowar** [comment]
> come?

Sto ancora finendo il codice, sarà all'interno di una variabile.

**Comment by Arrowar** [comment]
> come?

Aggiunto: get_only_link
