### ISSUE TITLE
error 409

### ISSUE THREAD

**Issue by dizplayy** [AstraeLabs/VibraVid#18]
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/11553812/1a36eaa5-82ec-4d1a-a691-7ac949e92520)

ricerca per 'all american'
seleziono 1 (la serie 'all american nightmare rapimento in california')

Esce errore 409

ps: dell'elenco che risulta dalla ricerca con all american, altri titoli hanno i 2 punti : nel nome, e provando un altro paio di quelli con i : entrambi risultano in errore 409, quindi ipotizzo sia il carattere : a rompere lo script.

Grazie

**Comment by Arrowar** [comment]
Si teoricamente è quello, se riesci a guardare dalle richieste di streming comunity in cosa viene convertito, saresti di grandissimo aiuto dato questa settimana non posso starci dietro.

**Comment by dizplayy** [comment]
io vedo l'url della pagina:
`7518-all-american-nightmare-rapimento-in-california`
mentre l'url del servizio streaming:
`https://vixcloud.co/embed/186636?token=51016afd1505a01f2123296900566a94&title=All+American+Nightmare%3A+Rapimento+in+California&referer=1&expires=1710964906&description=S1%3AE1+Parte+1%3A+Il+fidanzato&nextEpisode=1`

ti basta questo?
grazie

**Comment by Arrowar** [comment]
Si si da qua si vede che - viene convertito in %3A,qui però non è presente ":".

**Comment by dizplayy** [comment]
probabilmente alcuni simboli di punteggiatura vengono strippati. 
dallo stesso elenco risultante dalla ricerca iniziale indicata sopra, alcuni titoli hanno anche altri segni (virgole, apostrofi, etc).
Presumo abbiano un elenco di find replace nullo con questi elementi.
fa pure con comodo, e grazie sempre per il tuo lavoro.

**Comment by Arrowar** [comment]
Hanno cambiato le richieste, prossima settimana risolvo.

**Comment by Topicform** [comment]
Ciao Ghost... tu aiuti noi e io aiuto voi (magari ne eravate a conoscenza)...
Di tanto in tanto accade che al momento dell'unificazione degli stream.ts lo script si interrompe senza salvare il flusso nella dir "Movie". ho risolto unificando tutti gli stream .ts dalla dir "Temp" con queste 2 belle righette in Ffmpeg:
copy /b *.ts all.ts
ffmpeg -i all.ts -c copy all.mp4
Tuttavia se nel video interamente creato non appaiono i titoli di coda... Amen!
Buon lavoro sempre Ciaooo

**Comment by Arrowar** [comment]
Grazie mille si basta quel comando lo uso anche io nel join, se riesci scrivi i titoli che hanno problemi così se ho tempo settimana prossima gli controllo

**Comment by artifix100** [comment]
Ciao anche io errore 409 su qualsiasi ricerca

**Comment by Arrowar** [comment]
Settimana prossima risolvo, al momento sono molto occupato

**Comment by Arrowar** [comment]
Rispòtp

**Comment by artifix100** [comment]
ciao scusa , si è ripresentato sulle serie tv errore 409 , mentre per i film va in timeout

**Comment by Arrowar** [comment]
Ultima versione ?

**Comment by artifix100** [comment]
si l'ho riscaricata ieri , ho riprovato ora 
Find system => win32
FFmpeg => Add to system path



Insert word to search in all site: : troy
0 -> Troy - movie
1 -> Troy - La caduta di Troia - tv
2 -> Green Zone - movie
3 -> Little Nicky - Un diavolo a Manhattan - movie
4 -> Crank - movie
5 -> The Idol - tv
6 -> The Other Side - movie
7 -> Scherzi mortali - movie
8 -> The Nest (Il nido) - movie
9 -> Dash & Lily - tv
10 -> Il tagliaerbe - movie
11 -> I Goldbergs - tv
12 -> Trolls 3 - Tutti insieme - movie
13 -> Paura e delirio a Las Vegas - movie
14 -> Separazione - movie
15 -> On the Verge - Al limite - tv
16 -> Ballers - tv
17 -> Metal Lords - movie
18 -> Austin Powers - La spia che ci provava - movie
19 -> Il cacciatore e la regina di ghiaccio - movie
20 -> Kate - movie

Index to download: : 1

Tv select: Troy - La caduta di Troia
[17:09:06] Error: 409

**Comment by Arrowar** [comment]
> si l'ho riscaricata ieri , ho riprovato ora Find system => win32 FFmpeg => Add to system path
> 
> Insert word to search in all site: : troy 0 -> Troy - movie 1 -> Troy - La caduta di Troia - tv 2 -> Green Zone - movie 3 -> Little Nicky - Un diavolo a Manhattan - movie 4 -> Crank - movie 5 -> The Idol - tv 6 -> The Other Side - movie 7 -> Scherzi mortali - movie 8 -> The Nest (Il nido) - movie 9 -> Dash & Lily - tv 10 -> Il tagliaerbe - movie 11 -> I Goldbergs - tv 12 -> Trolls 3 - Tutti insieme - movie 13 -> Paura e delirio a Las Vegas - movie 14 -> Separazione - movie 15 -> On the Verge - Al limite - tv 16 -> Ballers - tv 17 -> Metal Lords - movie 18 -> Austin Powers - La spia che ci provava - movie 19 -> Il cacciatore e la regina di ghiaccio - movie 20 -> Kate - movie
> 
> Index to download: : 1
> 
> Tv select: Troy - La caduta di Troia [17:09:06] Error: 409

Risolto
