### ISSUE TITLE
Problemi con file che terminano in ...

### ISSUE THREAD

**Issue by Demential98** [AstraeLabs/VibraVid#184]
Ho notato utilizzando l'applicazione che alcuni file creano problemi fallendo il download completamente in quanto cerca di creare una cartella con ... e quando prova ad aprirla non riesce a trovarla, risolto :
aggiungendo al regex il singolo . 
modificando la funzione remove_special_characters nel file /Src/Util/os.py aggiungendo prima del re.compile

```
    ends_with_mp4 = input_string.endswith('.mp4')
    if ends_with_mp4:
        input_string = input_string[:-4]
```
e prima del return 
```
    if ends_with_mp4:
        cleaned_string += '.mp4'
```

**Comment by Arrowar** [comment]
Grazie mille stasera lo aggiungo subito.

**Comment by Arrowar** [comment]
Appena aggiusto fix
