### ISSUE TITLE
Modulo mancante

### ISSUE THREAD

**Issue by Wakolipo** [AstraeLabs/VibraVid#185]
Ciao a tutti,
da qualche giorno ricevo questo messaggio di errore all'esecuzione dello script _run.py_

`[00:51:28] Internet is available!                                                                                                                                                    os.py:289

System Summary:
Python: 3.13.0 (CPython x86_64) - Linux-6.11.7-300.fc41.x86_64-x86_64-with-glibc2.40 (OpenSSL 3.2.2 4 Jun 2024, glibc 2...4.0)
Exe versions: ffmpeg 7.0.2, ffprobe 7.0.2
Libraries: httpx-0.27.2, bs4-0.0.2, rich-13.9.4, tqdm-4.67.0, m3u8-6.0.0, psutil-5.9.8, unidecode-1.3.8, jsbeautifier-1.15.1, fake-useragent-1.5.1, qbittorrent-api-2024.11.69, 
python-qbittorrent-0.4.3, googlesearch-python-1.2.5

Checking GitHub version ...
Everything is up to date

StreamingCommunity has been downloaded 1273 times, but only 12.02% of users have starred it.
        Help the repository grow today by leaving a star and sharing it with others online!

Failed to import module 1337xx: No module named 'Crypto.Util.Padding'
Failed to import module altadefinizione: No module named 'Crypto.Util.Padding'
Failed to import module animeunity: No module named 'Crypto.Util.Padding'
Failed to import module bitsearch: No module named 'Crypto.Util.Padding'
Failed to import module cb01new: No module named 'Crypto.Util.Padding'
Failed to import module ddlstreamitaly: No module named 'Crypto.Util.Padding'
Failed to import module guardaserie: No module named 'Crypto.Util.Padding'
Failed to import module mostraguarda: No module named 'Crypto.Util.Padding'
Failed to import module piratebays: No module named 'Crypto.Util.Padding'
Failed to import module streamingcommunity: No module named 'Crypto.Util.Padding'
Category Legend: Anime | Film_serie | Film | Serie | Other
Insert category (): `

Ho risolto installando il modulo **pycryptodome** che però non risulta inserito nel file _requirements.txt_

Non so se questo il modo di procedere sia corretto, ma adesso funziona tutto.
Grazie per il lavoro svolto.

**Comment by Arrowar** [comment]
Si è il modo corretto.
