### ISSUE TITLE
missing attributes in the HLS_Dowloader class

### ISSUE THREAD

**Issue by zin8Eddine** [AstraeLabs/VibraVid#186]
# Download the episode
    r_proc = HLS_Downloader(
        #the problem: master_playlist = master_playlist
        m3u8_playlist=master_playlist,
        output_filename=os.path.join(mp4_path, mp4_name),
    ).start()

**Comment by Lovi-0** [comment]
File name with problem ?

**Comment by Arrowar** [comment]
Thank you fix.
