### ISSUE TITLE
Error ffmpeg

### ISSUE THREAD

**Issue by alexpic911** [AstraeLabs/VibraVid#19]
Salve a tutti,

ho riscontrato il seguente problema con il download, da cosa può dipendere?

![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/145979020/bac68cad-08ee-46a4-8c14-d0284aa03a6c)

**Comment by Arrowar** [comment]
Scrivimi nome della serie \ ep o film e settimana prossima vedo di risolvere

**Comment by Arrowar** [comment]
Risolto
