### ISSUE TITLE
scegliere categoria ma come?

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#197]
perchè ora è test_run.py invece di run.py?

grazie

**Comment by Arrowar** [comment]
> perchè ora è test_run.py invece di run.py?
> 
> grazie

Con pypi era necessario avere una cartella dove inserire tutto, tra qui anche run.py.

E per facilitare l'uso attraverso pypi e runnarare come era una volta (senza entrare direttamente in StreamingCommunity)  ho creato test_run.py che molto semplicemente richiama run.py.
