### ISSUE TITLE
Download parziale

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#198]
ciao, non capisco perchè mi scarica il video durante il download dice che so  [ 515 / 1397 ] 01:24 < 02:00, [ 380.96 < 1.01 GB | 3.56 MB/s ]
ma poi alla fine il file risulta di 68MB a volte 120 o cose così insomma non da il file completo, ma non da alcun errore.

**Comment by Arrowar** [comment]
Quanti retry fa ?

**Comment by ludogemma** [comment]
4 o 5

Il giorno dom 8 dic 2024 alle 20:12 Lovi ***@***.***> ha
scritto:

**Comment by Arrowar** [comment]
Che titolo su quale sito ?

**Comment by scaistar** [comment]
Anch'io ho notato che alcune puntate della serie Willy principe di Belair sono state scaricate parzialmente.
In questo momento ho aggiornato l'API e scaricato la puntata S2 E6 e mi viene salvato un file nominato così
willy-il-principe-di-bel-air_S02E06_Episodio 6_failed.mp4
Anche se a riguardarlo con VLC sembra completo fino alla fine

**Comment by Arrowar** [comment]
Ora provo a dare un'occhiata.

**Comment by Arrowar** [comment]
> Anch'io ho notato che alcune puntate della serie Willy principe di Belair sono state scaricate parzialmente.
> In questo momento ho aggiornato l'API e scaricato la puntata S2 E6 e mi viene salvato un file nominato così
> willy-il-principe-di-bel-air_S02E06_Episodio 6_failed.mp4
> Anche se a riguardarlo con VLC sembra completo fino alla fine
> 
> 

Fixato con la nuova versione.
