### ISSUE TITLE
Error 409

### ISSUE THREAD

**Issue by jacopeste05** [AstraeLabs/VibraVid#20]
ho riscontrato questo errore. penso accada ciò perchè hanno cambiato il dominio da .cz a .estate

**Comment by Arrowar** [comment]
Si

**Comment by Arrowar** [comment]
Risolto

**Comment by Topicform** [comment]
Ciao Ghost, scusami se inoltro i miei post magari nella sezione sbagliata, riscontro che circa ogni 2gg + o - nella schermata del cmd mi segnala la presenza di una nuova versione, pertanto io cancello la precedente e cosi via... tutto normale cosi giusto?... Grazie sempre per il tuo utilissimo impegno. Ciao.

**Comment by Arrowar** [comment]
Con il nuovo aggiornamento è stato risolto

**Comment by Topicform** [comment]
Grazie Ghost per la risposta celere

**Comment by Arrowar** [comment]
Di niente
