### ISSUE TITLE
Errno getaddrinfo

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#210]
Insert word to search in streamingcommunity: elevation
Checking url: https://streamingcommunity.family/

Test url: https://streamingcommunity.family/, error: [Errno 11001] getaddrinfo failed
Checking url: https://streamingcommunity.family/

Test url: https://streamingcommunity.family/, error: [Errno 11001] getaddrinfo failed
Checking url: https://it.tenorshare.com/duplica-schermo/streamingcommunity-nuovo-indirizzo.html

Do you want to auto site: streamingcommunity with domain: com [y/n] (y):

Buon Natale e grazie per questo utilissimo tool :)

**Comment by Arrowar** [comment]
Buona natale anche a te ludo il funzionamento non dipende da me.

Comunque è .prof

**Comment by ludogemma** [comment]
> Buona natale anche a te ludo il funzionamento non dipende da me.
> 
> Comunque è .prof

che significa "comunque è .prof"????

**Comment by Arrowar** [comment]
Il nuovo dominio di sc

**Comment by ludogemma** [comment]
ah e dove posso cambiarlo manualmente?

**Comment by Arrowar** [comment]
Sul config.json su site dove c'è scritto streamingcommunity

**Comment by ludogemma** [comment]
ok grazie ci provo

**Comment by ludogemma** [comment]
cambiare dominio ha funzionato, ma sbaglio o prima era possibile fare la ricerca di un titolo su tutti i siti contemporaneamente?

**Comment by Arrowar** [comment]
> cambiare dominio ha funzionato, ma sbaglio o prima era possibile fare la ricerca di un titolo su tutti i siti contemporaneamente?

Si ma è solo una cosa sperimentale

**Comment by ludogemma** [comment]
> > cambiare dominio ha funzionato, ma sbaglio o prima era possibile fare la ricerca di un titolo su tutti i siti contemporaneamente?
> 
> Si ma è solo una cosa sperimentale

si ma l'hai rimossa?

**Comment by Arrowar** [comment]
> > > cambiare dominio ha funzionato, ma sbaglio o prima era possibile fare la ricerca di un titolo su tutti i siti contemporaneamente?
> > 
> > 
> > Si ma è solo una cosa sperimentale
> 
> si ma l'hai rimossa?

è dentro la cartella Test ma controlla semplicemente se esiste quella parola per ogni sito.

cosi com'è non serve a molto

**Comment by ludogemma** [comment]
si ma come dovrei usare il big_search.py?

**Comment by Arrowar** [comment]
Entri nella cartella di Test e scrivi python big_search.py non cambia niente rispetto agli altri file.

**Comment by ludogemma** [comment]
> Entri nella cartella di Test e scrivi python big_search.py non cambia niente rispetto agli altri file.

se faccio come dici mi da questi errori:

https://prnt.sc/0KPvofkFp84B

**Comment by Arrowar** [comment]
Alla prossima versione arriva il fix
