### ISSUE TITLE
ERROR:root:Error extracting version: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by gaglio00** [AstraeLabs/VibraVid#212]
Sto riscontrando un problema in fase di download di film su Streamingcommunity, sostanzialmente non riesco ad usare nessuna funzionalità di questa categoria, mi crasha lo script, allego qui sotto qualche esempio di errore:

![image](https://github.com/user-attachments/assets/e1396981-583e-4cb5-8452-f1d50a1a4f00)

![image](https://github.com/user-attachments/assets/51f718f1-6cc0-410a-9ee3-98e0953951c0)

Qualunque ricerca faccia, dopo aver inserito la parola da cercare, crasha con questo errore:

**ERROR:root:Error extracting version: 'NoneType' object has no attribute 'get'**

Come posso fixare il problema?

Grazie mille in anticipo !

P.S.

Da altadefinizione funziona correttamente, però vorrei scaricarlo da streaming community perchè li c'è in 1080p:

![image](https://github.com/user-attachments/assets/359b0650-acbd-46b3-8958-c10e9f5f000c)

**Comment by Arrowar** [comment]
Alla prossima versione arriva il fix

**Comment by Arrowar** [comment]
> Sto riscontrando un problema in fase di download di film su Streamingcommunity, sostanzialmente non riesco ad usare nessuna funzionalità di questa categoria, mi crasha lo script, allego qui sotto qualche esempio di errore:
> 
> ![image](https://github.com/user-attachments/assets/e1396981-583e-4cb5-8452-f1d50a1a4f00)
> 
> ![image](https://github.com/user-attachments/assets/51f718f1-6cc0-410a-9ee3-98e0953951c0)
> 
> Qualunque ricerca faccia, dopo aver inserito la parola da cercare, crasha con questo errore:
> 
> **ERROR:root:Error extracting version: 'NoneType' object has no attribute 'get'**
> 
> Come posso fixare il problema?
> 
> Grazie mille in anticipo !
> 
> P.S.
> 
> Da altadefinizione funziona correttamente, però vorrei scaricarlo da streaming community perchè li c'è in 1080p:
> 
> ![image](https://github.com/user-attachments/assets/359b0650-acbd-46b3-8958-c10e9f5f000c)
> 

Ora funziona?

**Comment by gaglio00** [comment]
Ottimo, ora funziona correttamente !
Putroppo anche questo è in 720p... amen
Grazie mille !

![image](https://github.com/user-attachments/assets/471eb783-b222-47b6-8f88-411aaf36dc27)

non c'è modo di scaricarlo in 1080p ?

**Comment by Arrowar** [comment]
Se non è disponibile al momento no, dovresti prova di prima mattina

**Comment by gaglio00** [comment]
Ok grazie mille !
