### ISSUE TITLE
Download Process Fails on Termux android, solve with tqdm_use_large_bar 

### ISSUE THREAD

**Issue by valerio223** [AstraeLabs/VibraVid#216]
**Warning: Total Newbie Here!**
I’m a novice with both Python and Termux, so please be kind with me! 🙏
[I’m writing this in English, just for the sake of GitHub]

I’m encountering an issue with the package installed via Termux on my Xperia 1V (XQ-DQ54) running Android 14. The same version of the package works perfectly fine on my (much older) Xperia XZ1 running Android 9.

I’ve followed the instructions from the README and have been trying to use this package by running `test_run.py` from the parent directory "StreamingComm" (which is just "StreamingCommunity_api" renamed). Here's what's happening:

![Screenshot_20241231-130932_cr](https://github.com/user-attachments/assets/a7e90078-a331-4c47-afba-2837142d7b6d)

![Screenshot_20241231-131014_cr](https://github.com/user-attachments/assets/927da044-9dac-4e24-8c70-379d3dbd4ebf)

![Screenshot_20241231-131054_cr](https://github.com/user-attachments/assets/8d050cb5-9e72-42b1-8311-d4086e7b4d1c)

At this point, the download progress bar just stalls right from the start... a few minutes go by, until:

![Screenshot_20241231-131429](https://github.com/user-attachments/assets/9fbfb532-7f07-475f-ab96-6c7273865b87)

Then, I stop the download altogether:

![Screenshot_20241231-131458_cr](https://github.com/user-attachments/assets/13bb1358-2f23-458f-9743-c854b0f3769e)

![Screenshot_20241231-131736_cr](https://github.com/user-attachments/assets/88509d16-bf2d-4213-b648-f208bf66acc2)

![Screenshot_20241231-131743_cr](https://github.com/user-attachments/assets/013b1827-917b-4bcf-a922-7060f718bc16)

I expected the script to work the same way on both devices, but that’s not the case. While my Xperia 1V refuses to cooperate, the XZ1 works like a charm: 

![Screenshot_20241231-132335](https://github.com/user-attachments/assets/faff318e-bfd5-488c-829b-072681f0f469)

![Screenshot_20241231-132421](https://github.com/user-attachments/assets/3e513b2e-3d58-4a47-b0d5-e688641b8ac3)

![Screenshot_20241231-140749](https://github.com/user-attachments/assets/6c45648f-5f77-4bf5-98a0-f0e6791e3d86)

I’m not sure if this is an issue with Android 14, Termux, or the package itself. I've already gone through all possible app restrictions (both battery and network related) and disabled them, at least I think so. Settings->Developer Options ->Disable child process restrictions is ON, too. Any guidance would be greatly appreciated!

**Comment by Arrowar** [comment]
Is the version of the repository used on the Xperia XZ1 (Android 9) the same as the one on the Xperia 1V (Android 14), or are they different?

This could potentially be an issue with the newer versions.

**Comment by valerio223** [comment]
Thanks for the reply! The version of both the package [v2.1.0] and Termux [0.118.1 (1000)] is actually the same on both devices. Let me know if you need any more details.

**Comment by Arrowar** [comment]
Enable debug in the config.json file, for example: "debug": true.
Download an episode of a short series, and attach the generated app.log file afterward.

**Comment by valerio223** [comment]
Well I've enabled debug in the `config.json` file and tried to download an episode of a random short series (Knuckles, one season, 6 brief episodes) as you suggested. Attached is the `app.log` file. [Btw, both my devices aren't rooted].
[app.log](https://github.com/user-attachments/files/18282346/app.log)

**Comment by Arrowar** [comment]
Try to run update.py and download the same episode with error.

**Comment by valerio223** [comment]
I’m still experiencing the same issue... the download is stalling right from the start :/
Would you like me to re-run the package and attach the app.log file?

**Comment by Arrowar** [comment]
Set this in the config.json tqdm_use_large_bar to false

**Comment by Arrowar** [comment]
Any change ?

**Comment by valerio223** [comment]
Sorry, just got back to this now!
Well now downloads are no longer stalling! Thanks so much for the quick fix.
There’s just a small "gui" issue now with this " N/A N/A ", but I guess it's nothing major.
There’s also a warning about too many retries, though. Let me know if you’d like more feedback!

![Screenshot_20241231-173840_cr](https://github.com/user-attachments/assets/284b3857-c0f2-4ecc-aa16-c8f98867908b)

![Screenshot_20241231-174024_cr](https://github.com/user-attachments/assets/ccd7fb56-bdc3-4943-9f97-fa7ccc26c966)

**Comment by Arrowar** [comment]
If there's no issue, the speed on Android cannot be captured, so tqdm_use_large_bar should be disabled.

**Comment by valerio223** [comment]
> If there's no issue, the speed on Android cannot be captured, so tqdm_use_large_bar should be disabled.

Wow, no sugarcoating that, huh? Disabling `tqdm_use_large_bar` for good then! 
Thanks again, and Happy New Year! :)

**Comment by Arrowar** [comment]
> > If there's no issue, the speed on Android cannot be captured, so tqdm_use_large_bar should be disabled.
> 
> Wow, no sugarcoating that, huh? Disabling `tqdm_use_large_bar` for good then! 
> Thanks again, and Happy New Year! :)

You're welcome, happy new year / buon 2025 to you too. 😅
