### ISSUE TITLE
Audio fuory sync

### ISSUE THREAD

**Issue by dizplayy** [AstraeLabs/VibraVid#26]
Ciao,
i 2 episodi di "true detective", "stagione 4", episodi 1 e 2 appunto, riprodotti sul web dal player online sono ok, mentre una volta scaricati hannpo l'audio fuori sincrono di circa 1 secondo. Non ho idea del perchè, e non ho indizi da darti.
Le parti da scaricare, indicate "X su Y" corrispondono in quantità.

**Comment by Arrowar** [comment]
Ho appena provato vari metodi e non funzionano, unisce perfettamente audio[0] con video[0] ma da lo stesso problemi di sync, forse è un problema del sito ma non lo so per il momento è inrisolto.

**Comment by artifix100** [comment]
si scusa intervengo anche qui . stessa cosa su troy terzo episodio . fuori sincrono l'audio . mentre errore 409 risolto . naturalmente solo per segnalare . vedo poi se capita anche altrove.

**Comment by Arrowar** [comment]
Per il momento non so come intervenire dato che i file ts video e audio combaciano

**Comment by dizplayy** [comment]
> Per il momento non so come intervenire dato che i file ts video e audio combaciano

io ho notato, per i miei 2 episodi di test, che a/v sono syncati sui files temporanei fino ai ts 208~300 circa, poi sbroccano.
potrebbe essere dipendente dal fix di qualche giorno fa, quello seguente al fatto che il numero di parti da scaricare ipotetiche/reali non combaciava?
Inoltre googlando ho trovato che il parametro ffmpeg '-async ' potrebbe correggere il desync.
Butto li ipotesi per tentare qualche sorta di debug..

**Comment by Arrowar** [comment]
Ti riferivi a questo: https://superuser.com/questions/1668095/audio-on-ts-file-falls-progressively-out-of-sync, domani se riesco faccio dei tentativi ma da quello che dicono dipendono principalmente dagli fps del video che possono cambiare se non sbaglio

**Comment by Arrowar** [comment]
> > Per il momento non so come intervenire dato che i file ts video e audio combaciano
> 
> io ho notato, per i miei 2 episodi di test, che a/v sono syncati sui files temporanei fino ai ts 208~300 circa, poi sbroccano. potrebbe essere dipendente dal fix di qualche giorno fa, quello seguente al fatto che il numero di parti da scaricare ipotetiche/reali non combaciava? Inoltre googlando ho trovato che il parametro ffmpeg '-async ' potrebbe correggere il desync. Butto li ipotesi per tentare qualche sorta di debug..

Riesci a linkarmi la pagina dato che provando a usare sync mi da errori strani

**Comment by dizplayy** [comment]
Io avevo trovato questo
`https://videoconverter.wondershare.com/sync-audio/ffmpeg-sync-audio-and-video.html#:~:text=Correct%20FFmpeg%20Sync%20Audio%20to,second%20to%20fix%20the%20issue.`

**Comment by dizplayy** [comment]
ps: avviando "update" viene brasata anche la cartella 'videos', e sarebbe da evitare credo dato che credo in molti lascino li i file scaricati

**Comment by Arrowar** [comment]
> ps: avviando "update" viene brasata anche la cartella 'videos', e sarebbe da evitare credo dato che credo in molti lascino li i file scaricati

Appena risolto mancava una "s"

**Comment by Arrowar** [comment]
> https://videoconverter.wondershare.com/sync-audio/ffmpeg-sync-audio-and-video.html#:~:text=Correct%20FFmpeg%20Sync%20Audio%20to,second%20to%20fix%20the%20issue.

ho provato varie volte il comando `ffmpeg -i input.mp4 -itsoffset -15 -i input.mp4 -map 0:v -map 1:a -c copy output.mp4
` se hai più tempo di me per fare delle prove e riescie a trovare il timing giusto da cambiare con 15 sarebbe fantastico

**Comment by artifix100** [comment]
a me succede questo : 

![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/66954952/024ff232-e261-45d7-a0c5-a11ba2259c2b)
 per cui fino a un certo punto audio è giusto poi va fuori sincrono

**Comment by Arrowar** [comment]
> a me succede questo : 
> 
> ![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/66954952/024ff232-e261-45d7-a0c5-a11ba2259c2b)
>  per cui fino a un certo punto audio è giusto poi va fuori sincrono 

Questo è giusto il problema è trovare il giusto timing dello spostamento dell'audio

**Comment by dizplayy** [comment]
> > https://videoconverter.wondershare.com/sync-audio/ffmpeg-sync-audio-and-video.html#:~:text=Correct%20FFmpeg%20Sync%20Audio%20to,second%20to%20fix%20the%20issue.
> 
> ho provato varie volte il comando `ffmpeg -i input.mp4 -itsoffset -15 -i input.mp4 -map 0:v -map 1:a -c copy output.mp4 ` se hai più tempo di me per fare delle prove e riescie a trovare il timing giusto da cambiare con 15 sarebbe fantastico

su quale file va modificato?

**Comment by dizplayy** [comment]
Ho fatto un test con un software di editing video/audio.
Sul totale dell'episogio (ep. 3) ho compresso la traccia audio di 1.15 secondi e così l'audio risulta in sync.
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/11553812/9b0331a6-4c99-42a2-9831-1949caf59350)

**Comment by Arrowar** [comment]
Ok ma sia dall'inizio sia dalla fine era spostata di 1.15 secondi?

**Comment by dizplayy** [comment]
no, all'inizio è giusto. Ho stirato (compresso) la traccia audio totale, non l'ho sfasata e basta.

**Comment by Arrowar** [comment]
Che comprensione hai usato per farlo risultare giusto?

**Comment by Arrowar** [comment]
> no, all'inizio è giusto. Ho stirato (compresso) la traccia audio totale, non l'ho sfasata e basta.

Ma scaricando la traccia video ti dava qualche errore?

**Comment by dizplayy** [comment]
Nessun errore, ma ho controllati i ts e sono sfasati sempre più man mano che si sale di numero parti. QUindi il problema non sta nella join finale ma nel render dei singoli pezzi A/V.
L'episodio scaricato è lungo  56 minuti, 28 secondi e 15 centesimi, ovvero 3388.15 secondi.
Io ho compresso (velocizzato) l'audio di 1,15 secondi.
1.15 secondi, corrispondono a circa lo 0.0339% di 3388.15 secondi.
Altresì, se vogliamo la percentuale di compressione, si può dire che moltiplicando 3388.15 per circa 0.99937, si ottiene un valore vicino a 3386 che è la durata 'ridotta' dell'audio.
Questi sono tutti i numeri che si possono dedurre dall'esperimento manuale :)

**Comment by Arrowar** [comment]
Appena fixato, sono riuscito a trovare un'altra soluzione.

**Comment by dizplayy** [comment]
Confermo che funziona, sei un mito!
ps: c'è un doppio .mp4 alla fine del nome file ma non è un problema

**Comment by Arrowar** [comment]
Si si era tanto per ricordarmi dei file convertiti, ma non da problemi

**Comment by Arrowar** [comment]
> Confermo che funziona, sei un mito!
> ps: c'è un doppio .mp4 alla fine del nome file ma non è un problema

Grazie mille
