### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by Jogrin** [AstraeLabs/VibraVid#28]
Quando si effettua la ricerca del titolo la connessione va in timeout restituendo il seguente messaggio:
"TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond".
Ho provato anche a lanciare lo script di update ma continua ad andare in timeout.

**Comment by Ghost6446** [comment]
Ora dovrebbe essere risolto

**Comment by Arrowar** [comment]
Ora dovrebbe andare

**Comment by Jogrin** [comment]
l'errore c'è ancora, durante la chiamata Get rules lo script va in timeout restituendo lo stesso errore (allego screen)
![error](https://github.com/Ghost6446/StreamingCommunity_api/assets/4047040/53b0f6cc-46d5-404d-af8e-1c1f1cd8ed1a)

**Comment by Arrowar** [comment]
Ti consiglio di riprovare domani le possibilità sono due o hai una connessione lenta o hai inviato troppe richieste oggi.

**Comment by Jogrin** [comment]
ho riprovato, continua ad andare in timeout alla get rules, internet non è sicuramente (sono in fibra 1gb).

**Comment by Arrowar** [comment]
Se carichi streming comunity da browser, funzioan ?

**Comment by Jogrin** [comment]
si, riesco a vedere senza nessun problema

**Comment by Arrowar** [comment]
Prova a riscaricare dopo l'ultimo aggiornamento.

**Comment by Jogrin** [comment]
Niente, peccato perché fino a settimana scorsa riuscivo ad usarlo invece ultimamente nulla.. ci rinuncio grazie lo stesso! 😄

**Comment by Arrowar** [comment]
Di niente prova a usare le versioni vecchie.

**Comment by Arrowar** [comment]
Che errore da ora ?

**Comment by Jogrin** [comment]
volevo mandarti l'errore ma rilanciando lo script si è magicamente risolto tutto 😄

**Comment by Arrowar** [comment]
Perfetto allora mi sa che era un problema legato alla connessione
