### ISSUE TITLE
Add features ...

### ISSUE THREAD

**Issue by aspideaspide** [AstraeLabs/VibraVid#30]
Ciao, volevo chiederti se con questo script (che funziona alla grande, grazie) è possibile effettuare operazioni di questo tipo, ovviamente con i parametri necessari:
- invece di inserire il singolo episodio o l'intera stagione con *, è possibile inserire un range (es: 2-4)?
- è possibile specificare da linea di comando di 'saltare' nomi di file già presenti nel folder di download? (perchè attualmente scarica di nuovo il file e soltanto alla fine chiede se sovrascriverlo o meno).
Grazie

**Comment by Arrowar** [comment]
Si si può fare al prossimo aggiornamento gli aggiunto, quando la vedi chiusa questa issue dovremmo esserci

**Comment by Topicform** [comment]
Ciao Ghost, Credo (e spero tanto) di aver fatto bene... Allora: Ho scaricato la Versione 0.8.3.0 premendo anche su Upgrade.py - Ma all'avvio del CMD mi indica sempre la nuova versione, quando in precedenza mi scriveva a video "up to date". Questo è solo un appunto, nulla da indicare sulla funzionalità dello script a livello download. Grazie amico.
Saluti :)

**Comment by Arrowar** [comment]
Ora dovrebbe essere sparito il messaggio.

**Comment by Topicform** [comment]
Ok grazie caro👍

Il dom 4 feb 2024, 15:21 Ghost ***@***.***> ha scritto:

**Comment by Arrowar** [comment]
> Ciao, volevo chiederti se con questo script (che funziona alla grande, grazie) è possibile effettuare operazioni di questo tipo, ovviamente con i parametri necessari:
> 
> * invece di inserire il singolo episodio o l'intera stagione con *, è possibile inserire un range (es: 2-4)?
> * è possibile specificare da linea di comando di 'saltare' nomi di file già presenti nel folder di download? (perchè attualmente scarica di nuovo il file e soltanto alla fine chiede se sovrascriverlo o meno).
>   Grazie

Aggiunta
