### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'Error'

### ISSUE THREAD

**Issue by CannotTouch** [AstraeLabs/VibraVid#33]
E:\StreamingCommunity_api-main>python run.py

        _____ _                            _                                               _ _
        / ____| |                          (_)                                             (_) |
        | (___ | |_ _ __ ___  __ _ _ __ ___  _ _ __   __ _    ___ ___  _ __ ___  _   _ _ __  _| |_ _   _
        \___ \| __| '__/ _ \/ _` | '_ ` _ \| | '_ \ / _` |  / __/ _ \| '_ ` _ \| | | | '_ \| | __| | | |
        ____) | |_| | |  __/ (_| | | | | | | | | | | (_| | | (_| (_) | | | | | | |_| | | | | | |_| |_| |
        |_____/ \__|_|  \___|\__,_|_| |_| |_|_|_| |_|\__, |  \___\___/|_| |_| |_|\__,_|_| |_|_|\__|\__, |
                                                    __/ |                                         __/ |
                                                    |___/                                         |___/

Checking github version ...
=> Everything up to date
=> Last version: v0.8.3

StreamingCommunity_api was downloaded 41 times, but only 60.98% of You(!!) have starred it.
        Help the repository grow today, by leaving a star and sharing it to others online!

Checking ffmpeg ...
FFmpeg => Add to system path

Get rules ...
Rules => .li

Insert word to search in all site: : 7082
0 -> My Demon - tv

Index to download: : 0

Tv select: My Demon
Season find: 1

Insert season number: : 1
Ep: 1 => Vita fosca
Ep: 2 => Tutti hanno un demone nel cuore
Ep: 3 => Stringere la mano a un demone
Ep: 4 => Dolce ma pericoloso
Ep: 5 => Solo tu
Ep: 6 => Nella Ruota della Fortuna
Ep: 7 => Relazioni macchiate
Ep: 8 => La scelta fatale
Ep: 9 => La verità svelata
Ep: 10 => Uscire dal guscio
Ep: 11 => Un paradiso nefasto
Ep: 12 => La salvatrice della distruzione
Ep: 13 => Il passato, il peccato originale
Ep: 14 => Il nostro inferno personale
Ep: 15 => La fine del fato
Ep: 16 => Il nostro paradiso personale

Insert ep number or (*) to download all ep or [1-2] for a range of ep: : *
Download ep: 1 => Vita fosca
Quality select => 720p

[22:51:58] Download video ts                                                                                 m3u8.py:163
[22:51:59] Ts segments find => 1035                                                                           m3u8.py:84
Download  99% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 1.0/1.0 K [ 0:02:35 < 0:00:02 , 6 bytes/s ]
[22:54:34] Start join all file                                                                               m3u8.py:142
Traceback (most recent call last):
  File "E:\StreamingCommunity_api-main\Src\Util\FFmpeg\m3u8.py", line 144, in join
    ffmpeg.input(file_list_path, format='concat', safe=0).output(output_filename, c='copy', loglevel='quiet').run()
    ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\StreamingCommunity_api-main\run.py", line 61, in <module>
    main()
  File "E:\StreamingCommunity_api-main\run.py", line 51, in main
    download_tv(selected_title['id'], selected_title['slug'], site_version, domain)
  File "E:\StreamingCommunity_api-main\Src\Api\tv.py", line 170, in main_dw_tv
    dw_single_ep(tv_id, eps, int(ep['n'])-1, domain, token, tv_name, season_select)
  File "E:\StreamingCommunity_api-main\Src\Api\tv.py", line 133, in dw_single_ep
    dw_m3u8(m3u8_url, m3u8_url_audio, m3u8_key, mp4_path)
  File "E:\StreamingCommunity_api-main\Src\Util\FFmpeg\m3u8.py", line 195, in dw_m3u8
    M3U8Downloader(url, audio_url, key, output_filename).start()
  File "E:\StreamingCommunity_api-main\Src\Util\FFmpeg\m3u8.py", line 166, in start
    video_m3u8.join(self.video_path)
  File "E:\StreamingCommunity_api-main\Src\Util\FFmpeg\m3u8.py", line 145, in join
    except ffmpeg.Error as e:
           ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'Error'

E:\StreamingCommunity_api-main>

**Comment by Arrowar** [comment]
Do you add ffmpeg in path windows ?

**Comment by CannotTouch** [comment]
yes
![Immagine 2024-02-12 074232](https://github.com/Ghost6446/StreamingCommunity_api/assets/84774326/562c5c9c-9dc6-426f-aa7d-2be7dbcd3488)

E:\StreamingCommunity_api-main>ffmpeg -version
ffmpeg version 6.1.1-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      58. 29.100 / 58. 29.100
libavcodec     60. 31.102 / 60. 31.102
libavformat    60. 16.100 / 60. 16.100
libavdevice    60.  3.100 / 60.  3.100
libavfilter     9. 12.100 /  9. 12.100
libswscale      7.  5.100 /  7.  5.100
libswresample   4. 12.100 /  4. 12.100
libpostproc    57.  3.100 / 57.  3.100

E:\StreamingCommunity_api-main>

**Comment by Arrowar** [comment]
Ok today I will try.

**Comment by Arrowar** [comment]
Remove "ffmpeg." from except ffmpeg.Error as e:

**Comment by CannotTouch** [comment]
sorry i didn't understant what to do... Do I need delete the ffmpeg directory E:\StreamingCommunity_api-main\Src\Util\FFmpeg ?

**Comment by Arrowar** [comment]
No

**Comment by Arrowar** [comment]
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/62809003/83592054-b3c0-4925-be21-099304455337)
It work perfectly try run "pip install ffmpeg-python==0.2.0"

**Comment by CannotTouch** [comment]
E:\StreamingCommunity_api-main>pip install ffmpeg-python==0.2.0
Requirement already satisfied: ffmpeg-python==0.2.0 in c:\users\bla\appdata\local\programs\python\python312\lib\site-packages (0.2.0)
Requirement already satisfied: future in c:\users\bla\appdata\local\programs\python\python312\lib\site-packages (from ffmpeg-python==0.2.0) (0.18.3)

E:\StreamingCommunity_api-main>python run.py

        _____ _                            _                                               _ _
        / ____| |                          (_)                                             (_) |
        | (___ | |_ _ __ ___  __ _ _ __ ___  _ _ __   __ _    ___ ___  _ __ ___  _   _ _ __  _| |_ _   _
        \___ \| __| '__/ _ \/ _` | '_ ` _ \| | '_ \ / _` |  / __/ _ \| '_ ` _ \| | | | '_ \| | __| | | |
        ____) | |_| | |  __/ (_| | | | | | | | | | | (_| | | (_| (_) | | | | | | |_| | | | | | |_| |_| |
        |_____/ \__|_|  \___|\__,_|_| |_| |_|_|_| |_|\__, |  \___\___/|_| |_| |_|\__,_|_| |_|_|\__|\__, |
                                                    __/ |                                         __/ |
                                                    |___/                                         |___/

Checking github version ...
=> Everything up to date
=> Last version: v0.8.3


StreamingCommunity_api was downloaded 41 times, but only 63.41% of You(!!) have starred it.
        Help the repository grow today, by leaving a star and sharing it to others online!


Checking ffmpeg ...
FFmpeg => Add to system path


Get rules ...
Rules => .li

Insert word to search in all site: : 7082
0 -> My Demon - tv

Index to download: : 0

Tv select: My Demon
Season find: 1

Insert season number: : 1
Ep: 1 => Vita fosca
Ep: 2 => Tutti hanno un demone nel cuore
Ep: 3 => Stringere la mano a un demone
Ep: 4 => Dolce ma pericoloso
Ep: 5 => Solo tu
Ep: 6 => Nella Ruota della Fortuna
Ep: 7 => Relazioni macchiate
Ep: 8 => La scelta fatale
Ep: 9 => La verità svelata
Ep: 10 => Uscire dal guscio
Ep: 11 => Un paradiso nefasto
Ep: 12 => La salvatrice della distruzione
Ep: 13 => Il passato, il peccato originale
Ep: 14 => Il nostro inferno personale
Ep: 15 => La fine del fato
Ep: 16 => Il nostro paradiso personale

Insert ep number or (*) to download all ep or [1-2] for a range of ep: : *
Download ep: 1 => Vita fosca
Quality select => 720p


[14:59:56] Download video ts                                                                                 m3u8.py:163
[14:59:57] Ts segments find => 1035                                                                           m3u8.py:84
Download  99% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 1.0/1.0 K [ 0:02:44 < 0:00:02 , 7 bytes/s ]
[15:02:41] Start join all file                                                                               m3u8.py:142
Traceback (most recent call last):
  File "E:\StreamingCommunity_api-main\Src\Util\FFmpeg\m3u8.py", line 144, in join
    ffmpeg.input(file_list_path, format='concat', safe=0).output(output_filename, c='copy', loglevel='quiet').run()
    ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\StreamingCommunity_api-main\run.py", line 61, in <module>
    main()
  File "E:\StreamingCommunity_api-main\run.py", line 51, in main
    download_tv(selected_title['id'], selected_title['slug'], site_version, domain)
  File "E:\StreamingCommunity_api-main\Src\Api\tv.py", line 170, in main_dw_tv
    dw_single_ep(tv_id, eps, int(ep['n'])-1, domain, token, tv_name, season_select)
  File "E:\StreamingCommunity_api-main\Src\Api\tv.py", line 133, in dw_single_ep
    dw_m3u8(m3u8_url, m3u8_url_audio, m3u8_key, mp4_path)
  File "E:\StreamingCommunity_api-main\Src\Util\FFmpeg\m3u8.py", line 195, in dw_m3u8
    M3U8Downloader(url, audio_url, key, output_filename).start()
  File "E:\StreamingCommunity_api-main\Src\Util\FFmpeg\m3u8.py", line 166, in start
    video_m3u8.join(self.video_path)
  File "E:\StreamingCommunity_api-main\Src\Util\FFmpeg\m3u8.py", line 145, in join
    except ffmpeg.Error as e:
           ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'Error'

E:\StreamingCommunity_api-main>

**Comment by CannotTouch** [comment]
Solved. Was a Python version problem

Solution:
Install Python 3.9
`py -3.9 -m pip install -r requirements.txt`
`py -3.9 -m pip install -U ffmpeg-python==0.2.0`
`py -3.9 run.py`

thanks for the support

**Comment by Arrowar** [comment]
Perfect
