### ISSUE TITLE
Error 409

### ISSUE THREAD

**Issue by UrloMythus** [AstraeLabs/VibraVid#35]
I have got error 409 while downloading "The Crown". 
```
Tv select: The Crown
 Error: 409        
```
Thanks again for your work, and don't worry if you can't fix it. 
P.S. It just happens with this particular TV show.   Update: Now it happens with Berlin too (a show that I was  able to download before)

**Comment by Arrowar** [comment]
This week i will test.

**Comment by UrloMythus** [comment]
Sorry my bad, no need to. Found out It just needed to be updated. Tho it was weird I was being able to download some movies since from what I can see that errors refers to bad domain.

**Comment by Arrowar** [comment]
Perfect.
