### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by CannotTouch** [AstraeLabs/VibraVid#37]
With the 0.8.5. https://github.com/Ghost6446/StreamingCommunity_api/commit/dee1eeec093eb2647a034bbfeb4f0ef0d489658a and Python 3.11.8

E:\StreamingCommunity_api-main>py -3.11 run.py

        _____ _                            _                                               _ _
        / ____| |                          (_)                                             (_) |
        | (___ | |_ _ __ ___  __ _ _ __ ___  _ _ __   __ _    ___ ___  _ __ ___  _   _ _ __  _| |_ _   _
        \___ \| __| '__/ _ \/ _` | '_ ` _ \| | '_ \ / _` |  / __/ _ \| '_ ` _ \| | | | '_ \| | __| | | |
        ____) | |_| | |  __/ (_| | | | | | | | | | | (_| | | (_| (_) | | | | | | |_| | | | | | |_| |_| |
        |_____/ \__|_|  \___|\__,_|_| |_| |_|_|_| |_|\__, |  \___\___/|_| |_| |_|\__,_|_| |_|_|\__|\__, |
                                                    __/ |                                         __/ |
                                                    |___/                                         |___/

Checking github version ...
=> Everything up to date
=> Last version: v0.8.5

StreamingCommunity_api was downloaded 2 times, but only 1550.0% of You(!!) have starred it.
        Help the repository grow today, by leaving a star and sharing it to others online!

Checking ffmpeg ...
FFmpeg => Find

Get rules ...
Test domain => express
Rules => .express

Insert word to search in all site: : my d
0 -> My Dog Stupid - Il mio cane Stupido - movie
1 -> My Demon - tv
2 -> I Love My Dad - movie
3 -> L'appuntamento natalizio di papà - movie
4 -> Mio papà a caccia di alieni - tv
5 -> Ho ucciso mio padre - tv
6 -> Drive My Car - movie
7 -> Più tardi al buio - movie
8 -> All my friends are dead - movie
9 -> Il drago di mio padre - movie
10 -> Blue My Mind - Il segreto dei miei anni - movie
11 -> Fuga dalla realtà - movie
12 -> La custode di mia sorella - movie
13 -> Scuola media: Gli anni peggiori della mia vita - movie
14 -> Le Avventure di A.R.I.: Il Mio Amico Robot - movie
15 -> Pepsi, dov'è il mio jet? - tv
16 -> My Holo Love - tv
17 -> My Name - tv
18 -> My Son - movie
19 -> My First First Love - tv
20 -> My Fair Lady - movie

Index to download: : 1

Tv select: My Demon
Season find: 1

Insert season number: : 1
Ep: 1 => Vita fosca
Ep: 2 => Tutti hanno un demone nel cuore
Ep: 3 => Stringere la mano a un demone
Ep: 4 => Dolce ma pericoloso
Ep: 5 => Solo tu
Ep: 6 => Nella Ruota della Fortuna
Ep: 7 => Relazioni macchiate
Ep: 8 => La scelta fatale
Ep: 9 => La verità svelata
Ep: 10 => Uscire dal guscio
Ep: 11 => Un paradiso nefasto
Ep: 12 => La salvatrice della distruzione
Ep: 13 => Il passato, il peccato originale
Ep: 14 => Il nostro inferno personale
Ep: 15 => La fine del fato
Ep: 16 => Il nostro paradiso personale

Insert ep number or (*) to download all ep or [1-2] for a range of ep: : *
Download ep: 1 => Vita fosca
Quality select => 1080p
Traceback (most recent call last):
  File "E:\StreamingCommunity_api-main\run.py", line 64, in <module>
    main()
  File "E:\StreamingCommunity_api-main\run.py", line 54, in main
    download_tv(selected_title['id'], selected_title['slug'], site_version, domain)
  File "E:\StreamingCommunity_api-main\Src\Api\tv.py", line 177, in main_dw_tv
    dw_single_ep(tv_id, eps, int(ep['n'])-1, domain, token, tv_name, season_select)
  File "E:\StreamingCommunity_api-main\Src\Api\tv.py", line 135, in dw_single_ep
    m3u8_url_audio, m3u8_playlist_content = get_m3u8_playlist(json_win_video, json_win_param, tv_name, season_select, index_ep_select+1, eps[index_ep_select]['name'], token_render)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

thanks for support

**Comment by Arrowar** [comment]
Fix

**Comment by dizplayy** [comment]
Per curiosità, che video mi sono perso su YT?

**Comment by Arrowar** [comment]
> Per curiosità, che video mi sono perso su YT?

Nessuno, tranquillo ho pubblicato qualche video mentre lo programmavo ma ancora le versioni basi ed il semplice tutorial su come eseguirlo e per mostrare che funziona tutto.

**Comment by CannotTouch** [comment]
Grazie per il fix. I video li scarica nuovamente, ma niente sub 
[18:57:19] No subtitle find

serie 7082

**Comment by Arrowar** [comment]
> Grazie per il fix. I video li scarica nuovamente, ma niente sub [18:57:19] No subtitle find
> 
> serie 7082

Nome della serie e episodio ?

**Comment by CannotTouch** [comment]
my demon ho provato i primi due episodi

**Comment by Arrowar** [comment]
> my demon ho provato i primi due episodi

Risolto, mancava una funzione.

**Comment by CannotTouch** [comment]
TI ringrazio, ora scarica anche tutti i sottotitoli tranne quelli italiani :D
(che ci sono sul sito)

Download ep: 1 => Vita fosca
Quality select => 1080p
[22:06:37] Download subtitle: kor                                                                         my_m3u8.py:126
[22:06:39] Download subtitle: ger                                                                         my_m3u8.py:126
[22:06:41] Download subtitle: eng                                                                         my_m3u8.py:126
[22:06:43] Download subtitle: fre                                                                         my_m3u8.py:126
[22:06:45] Download subtitle: ukr                                                                         my_m3u8.py:126
[22:06:46] Download video ts                                                                              my_m3u8.py:339

**Comment by Arrowar** [comment]
> TI ringrazio, ora scarica anche tutti i sottotitoli tranne quelli italiani :D
> (che ci sono sul sito)
> 
> Download ep: 1 => Vita fosca
> Quality select => 1080p
> [22:06:37] Download subtitle: kor                                                                         my_m3u8.py:126
> [22:06:39] Download subtitle: ger                                                                         my_m3u8.py:126
> [22:06:41] Download subtitle: eng                                                                         my_m3u8.py:126
> [22:06:43] Download subtitle: fre                                                                         my_m3u8.py:126
> [22:06:45] Download subtitle: ukr                                                                         my_m3u8.py:126
> [22:06:46] Download video ts                                                                              my_m3u8.py:339
> 

Ora non solo al pc comunque per risolvere rimuovi "ita" in questa riga https://github.com/Ghost6446/StreamingCommunity_api/blob/main/Src%2FLib%2FFFmpeg%2Fmy_m3u8.py#L122

**Comment by CannotTouch** [comment]
Perfetto, grazie

**Comment by CannotTouch** [comment]
> > TI ringrazio, ora scarica anche tutti i sottotitoli tranne quelli italiani :D
> > (che ci sono sul sito)
> > Download ep: 1 => Vita fosca
> > Quality select => 1080p
> > [22:06:37] Download subtitle: kor                                                                         my_m3u8.py:126
> > [22:06:39] Download subtitle: ger                                                                         my_m3u8.py:126
> > [22:06:41] Download subtitle: eng                                                                         my_m3u8.py:126
> > [22:06:43] Download subtitle: fre                                                                         my_m3u8.py:126
> > [22:06:45] Download subtitle: ukr                                                                         my_m3u8.py:126
> > [22:06:46] Download video ts                                                                              my_m3u8.py:339
> 
> Ora non solo al pc comunque per risolvere rimuovi "ita" in questa riga https://github.com/Ghost6446/StreamingCommunity_api/blob/main/Src%2FLib%2FFFmpeg%2Fmy_m3u8.py#L122

Ciao @Ghost6446 la 0.9.0 continua a non scaricare i sub ita. Grazie per il supporto

**Comment by Arrowar** [comment]
Ora dovrebbe andare

**Comment by CannotTouch** [comment]
Confermo li nomina come auto ma li scarica. grazie.
