### ISSUE TITLE
Idea new repo ...

### ISSUE THREAD

**Issue by RobbieDS** [AstraeLabs/VibraVid#39]
si puo aggiungere anche il dominio https://www.animeunity.to/ la sezione anime di streaming comunity? grazie

**Comment by Arrowar** [comment]
Se ho tempo faro un altra reposity

**Comment by RobbieDS** [comment]
grazie mille.. immgino non sia molto complicato, visto che è creato e gestito dagli stessi... grazie e attendo impaziente :)

**Comment by Arrowar** [comment]
> grazie mille.. immgino non sia molto complicato, visto che è creato e gestito dagli stessi... grazie e attendo impaziente :)

Ho appena finito di fare il reverse dell api quindi ci vorrà ancora un po' prima dell'aggiornamento.

**Comment by Arrowar** [comment]
> grazie mille.. immgino non sia molto complicato, visto che è creato e gestito dagli stessi... grazie e attendo impaziente :)

Aggiunga in pre release.
