### ISSUE TITLE
Fix audio, video download ...

### ISSUE THREAD

**Issue by antvinz** [AstraeLabs/VibraVid#40]
salve, mi capita spesso che quando scarico un episodio che viene scaricato a poco più della metà ( ex episodio che dura 30 minuti ne scarica circa 20)

**Comment by antvinz** [comment]
inoltre la selezione multipla degli episodi non funziona (ex quando vuoi solo ep 3-10), crasha

**Comment by Arrowar** [comment]
Riesci a fornirmi qualche esempio, il log del terminale e come l'hai scritto il comando ?

**Comment by Stormsz0** [comment]
Salve ho il suo stesso problema, cioè che non scarica completamente gli episodi, arriva quasi sempre tra il 98-99% (inserisco screen in allegato). Ma comunque gli episodi sembrano essere integri quindi potrebbe essere solo un problema di logging, tranne per l'ultimo episodio che ho scaricato, il download dell'audio è arrivato fino al 96% e quindi gli ultimi 15 secondi di episodi erano senza audio

![Cattura](https://github.com/Ghost6446/StreamingCommunity_api/assets/87542900/5d5e9fba-1d58-4f4e-ba8d-2167992aa9bc)

**Comment by Arrowar** [comment]
Il 99 è un bug grafico in realtà gli scarica tutti ma non esegue l'aggiornamento l'ultima volta per il 96% questa settimana controllo

**Comment by antvinz** [comment]
Scusa se non ti ho risposto subito, ad esempio questo episodio che ho provato a salvare, viene scaricato in questo caso per metà( 15 min) a volte invece qualcosa in più ( 20,24 min) , su 5 episodi,3 li scarica cosi e 2 interi. Ho provato sia si linux che su Windows, e capita spesso su Windows, su linux quasi mai. ( forse è un problema di fffmpeg?)
![Cattura](https://github.com/Ghost6446/StreamingCommunity_api/assets/160575540/13e659dd-780d-4c00-bda1-495a0d5fbddc)
Inoltre ti volevo segnalare che quando cè qualche carattere speciale, l app va in crash 
![Cattura3](https://github.com/Ghost6446/StreamingCommunity_api/assets/160575540/8af926cc-4904-4c24-803a-38e72431f868)
![Cattura2](https://github.com/Ghost6446/StreamingCommunity_api/assets/160575540/c071d4eb-d62e-4bcd-91ea-ab7c35cdcb49)


Infine il problema che ti ho segnalato di selezionare più episodi è stato un mio errore, pensavo si dovesse solo scrivere il numero diviso dal trattino e non compresa di parentesi graffa

**Comment by Arrowar** [comment]
Si penso anche io che sia un problema di ffmpeg per windows, nel caso che che versione hai per Linux. Per i caratteri speciali l'ho fixata ieri con url parse sul refer di decryption per key, ma devo ancora fare il commit finale dato che ho ancora diversi problemi.

**Comment by antvinz** [comment]
ffmpeg 5.1.2 su ubuntu

**Comment by Arrowar** [comment]
> ffmpeg 5.1.2 su ubuntu

Invece della libreria di ffmpeg-python?
