### ISSUE TITLE
Error saving MP4: None

### ISSUE THREAD

**Issue by Samue1e** [AstraeLabs/VibraVid#41]
Premetto che sono su Windows, non so se valga anche su Linux

Il problema si verifica alla riga 320 di my_m3u8.py
`ffmpeg.input(file_list_path, format='concat', safe=0).output(output_filename, c='copy', loglevel='quiet').run()
`
Cercando online ho trovato che il file di testo in input file_list_path deve essere scritto con i front slash invece che con i backslash e effettivamente cambiando la riga in
`ffmpeg.input(file_list_path.replace("\\", "/"), format='concat', safe=0).output(output_filename, c='copy', loglevel='quiet').run()
`
tutto funziona perfettamente.

**Comment by Arrowar** [comment]
Ok perfetto allora lo aggiungerò, tuttavia non se questo possa funzionare anche per linux, se hai tempo riesci a controllarmi, che in file_list_path precedente non erano presenti spazi ?

**Comment by Samue1e** [comment]
Non c'erano spazi.
In alternativa ho provato a mettere i path assoluti in file_list.txt, quindi cambiando
```
relative_path = os.path.relpath(os.path.join(self.temp_folder, ts_file), current_dir)
f.write(f"file '{relative_path}'\n")
```
(righe 315-316)
con 
```
absolute_path = os.path.abspath(os.path.join(self.temp_folder, ts_file))
f.write(f"file '{absolute_path}'\n")
```
e ha funzionato anche senza dover fare il replace alla riga 320 (quindi le uniche righe cambiate rispetto al codice in repo sono 315-316).
Penso che questo non crei problemi neanche su Linux.

**Comment by Arrowar** [comment]
Grazie mille, appena finisco di sistemare gli ultimi dettagli pubblico la nuova versione con commenti, classi e una gestione migliore.
