### ISSUE TITLE
Fix audio ....

### ISSUE THREAD

**Issue by Pedruuxx** [AstraeLabs/VibraVid#42]
Evidenzio un problema nella creazione del file video finale che coinvolge file vecchi e file recenti appena caricati nella piattaforma. Porto alcuni esempi:
1- Scaricando le prime stagioni (S01 e S02) delle serie TV Mare Fuori, l'audio risulta interrotto e spezzato ogni 30 secondi.
Probabilmente perchè son file più vecchi. 
Allora ho provato con file più recenti.
2- Provando nuovi episodi appena aggiunti nella piattaforma come ad esempio episodio 5 stagione 4 di True Detective, si nota che il file audio che scarica ha una durata inferiore (circa 56 minuti) a quella del video (circa 1h) per cui gli ultimi 5 minuti sono silenziati (video regolare senza audio).
3- Altro esempio recente. Nella nuova stagione 3 della serie TV The Warrior, il primo episodio è scaricato in modo impeccabile, il secondo ha audio fuori sincronizzazione
Non ho idea del motivo ma non ho capito come mai alcuni episodi sono scaricati perfettamente ed altri hanno problemi

**Comment by Arrowar** [comment]
Grazie mille per il chiarimento, questa settimana provo a risolvere in definitiva il problema.

**Comment by Pedruuxx** [comment]
![Streamingcommunity](https://github.com/Ghost6446/StreamingCommunity_api/assets/155879404/3441cc28-72a7-4393-9814-639cf7b65880)

**Comment by Pedruuxx** [comment]
Ciao Ghost! oggi ho provato a fare un tentativo con un nuovo episodio appena caricato sulla piattaforma (vedi screenshot). Scaricando l'episodio 1, ho notato che nei primi 53 minuti video e audio sono ottimi e ben sincronizzati. Dal minuto 53 il video prosegue mentre l'audio comincia ad essere incomprensibile, come se ci fosse una errata unione dei diversi frammenti audio. 
Ci sono cinque secondi di rumore del mare poi cinque secondi di un dialogo e poi altri cinque secondi di un dialogo audio preso da un'altra scena il tutto in sequenza completamente fuory sync dall' immagine video.

**Comment by Arrowar** [comment]
Ok oggi provo e dopo ti dico con la nuova versione.

**Comment by Arrowar** [comment]
> Ciao Ghost! oggi ho provato a fare un tentativo con un nuovo episodio appena caricato sulla piattaforma (vedi screenshot). Scaricando l'episodio 1, ho notato che nei primi 53 minuti video e audio sono ottimi e ben sincronizzati. Dal minuto 53 il video prosegue mentre l'audio comincia ad essere incomprensibile, come se ci fosse una errata unione dei diversi frammenti audio. Ci sono cinque secondi di rumore del mare poi cinque secondi di un dialogo e poi altri cinque secondi di un dialogo audio preso da un'altra scena il tutto in sequenza completamente fuory sync dall' immagine video.

![immagine_2024-02-27_195348201](https://github.com/Ghost6446/StreamingCommunity_api/assets/62809003/3f8311c5-5f20-411b-968a-cf73ac06be2f)

Forse questa settimana risolvo con la nuova versione

**Comment by Pedruuxx** [comment]
Con la nuova versione 0.8.9 persistono problemi del file audio che risulta interrotto ogni 20 secondi per la stagione 1 di Only Murder in The Building o prime stagioni di Mare Fuori. Ho notato che in questi casi non scarica audio.ts ma solo il file video

**Comment by Arrowar** [comment]
Non scaricando i file audio .ts non dovrebbe esserci problemi, prova ad aprilo con vlc.

**Comment by Arrowar** [comment]
> Con la nuova versione 0.8.9 persistono problemi del file audio che risulta interrotto ogni 20 secondi per la stagione 1 di Only Murder in The Building o prime stagioni di Mare Fuori. Ho notato che in questi casi non scarica audio.ts ma solo il file video

Provato mare fuori stagione 1 ep 1 con https://github.com/Ghost6446/StreamingCommunity_api/releases/tag/v0.8.9 e funziona. Prova ad aggiornare ffmpeg all'ultima versione.
