### ISSUE TITLE
fix CPU 99%

### ISSUE THREAD

**Issue by Paura7** [AstraeLabs/VibraVid#43]
Ciao, prima di tutto volevo ringraziarti per questo fantastico script che uso molto spesso, ho notato che durante il download la CPU viene maxxata al 99%, rendendo anche abbastanza irresponsivo il sistema (Windows nel mio caso), sarebbe possibile aggiungere un limite su quanti thread si vogliono assegnare durante il download o comunque limitare questo problema in altri modi? Grazie!

**Comment by Arrowar** [comment]
Certamente dentro util / my_lib / my_m3u8 dovresti trovare la variabile WORKERS di default se non sbaglio è140 o 40, ti consiglio di cambiarla a 8 o 4 in correlazione con i thread della tua cpu.
