### ISSUE TITLE
Log Download Subtitle appare 2 volte

### ISSUE THREAD

**Issue by Fede14it** [AstraeLabs/VibraVid#44]
Come puoi vedere dallo screenshot download subtitle solo per l'inglese appare 2 volte ma sembra essere un bug grafico
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/115009551/bf3e77a1-2929-48ec-a7ca-74368c0cdcf4)
Inoltre volevo chiederti se possiamo fare una chiacchierata su Discord in quanto sto aggiungendo dei cambiamenti
Il mio username é fede14

**Comment by Arrowar** [comment]
Certo dopo ti aggiungo, praticamente l'ho riscritta quasi tutta e sto finendo le ultime cose.
