### ISSUE TITLE
Join ts audio with video

### ISSUE THREAD

**Issue by Jefry99** [AstraeLabs/VibraVid#5]
Potresti provare a spiegarmi come mai quando si scaricano le serie bisogna scaricare separatamente l'audio, mentre con i film questo passaggio non è necessario? Mi sono spulciato il più possibile il codice ed anche ispezionando streamingcommunity ed i file di vixcloud.co al suo interno non riesco a capire come mai ci sia questa differenza. Grazie.

**Comment by Arrowar** [comment]
Sincreamente non lo ma, ho notato che per alcune serie specialmente quelle pià nuove, l'audio non è inserito direttamente nel file m3u8, ma bisogna fare un'altra richiesta per avere tutti gli audio disponibili, forse ora non c'è non ho controllato recentemente.

**Comment by Jefry99** [comment]
Ho provato a scaricare per test un episodio si una stagione appena uscita, ed uno di una stagione più vecchia (dr house) ed in nessuno dei video ho l'audio. Allora è una semplice questione di dover fare 2 richieste separate? Perchè se è così non penso si possa fare in un passaggio solo come per i film

**Comment by Arrowar** [comment]
Io ero partito con la serie "Person of Interest", e nelle prime 3 stagioni non dava problemi, poi con le ultime mancava l'audio. Ho guardato le varie richieste ed effettivamente nelle ultime due faceva una richiesta in più per richiedere l'audio separatamente, tipo questa: "https://vixcloud.co/playlist/179589type=audio&rendition=ita&token=uoOCK2vVO9scRaODAeE7yw&expires=1709548644", allora ho risolto scaricando e unendo, ma probabilmente c'è un modo migliore di unirlo usando ffmpeg e ts con video e audio. 
Inoltre alcune serie hanno l'accento, quindi bisogna convertirle tutte nel formatato standard utf-8 se no la richiesta non funziona. Appena ho tempo lo aggiungerò.

**Comment by Jefry99** [comment]
Ah okay, grazie mille. Adesso guardo se riesco ad unire direttamente i ts ed audio per evitare il join che porta via un sacco di tempo e risorse.

**Comment by Arrowar** [comment]
Grazie mille se riesci, dato che porterebbe un notevole miglioramento nel tempo e nell'uso della cpu.

**Comment by Jefry99** [comment]
Ci sono riuscito ma il codice che ho scritto è incasinato a dir poco. Appena ho tempo lo sistemo.

**Comment by Arrowar** [comment]
Grazie mille, tempo di provare e ricarivo la nuova versione dove fixo i problemi di path con linux e i nome latin

**Comment by Arrowar** [comment]
Nuova versione ora. Ho cambiato tutta la classe m3u8, forse ora ti verra meglio, ed il join dei file ts ci mette molto meno.

**Comment by Arrowar** [comment]
> Ci sono riuscito ma il codice che ho scritto è incasinato a dir poco. Appena ho tempo lo sistemo.

Fatto anche io

**Comment by Jefry99** [comment]
Ottimo!
