### ISSUE TITLE
Option change quality ...

### ISSUE THREAD

**Issue by Skulp55** [AstraeLabs/VibraVid#50]

**Comment by Ghost6446** [comment]
Si appena riesco carico l'update con la versione 1080

**Comment by Arrowar** [comment]
> _No description provided._

Di dovrebbe essere già

**Comment by Skulp55** [comment]
> > _No description provided._
> 
> Di dovrebbe essere già

E come si fa?

**Comment by Arrowar** [comment]
Se è presenta la scarica se no scala alla prima migliore

**Comment by Skulp55** [comment]
> Se è presenta la scarica se no scala alla prima migliore

Quindi scarica direttamente a 1080p se non c'è un altra qualità (c'è ad altre qualità)

**Comment by Skulp55** [comment]
> > Se è presenta la scarica se no scala alla prima migliore
> 
> Quindi scarica direttamente a 1080p se non c'è un altra qualità (c'è ad altre qualità)

E quindi non si può cambiare

**Comment by Arrowar** [comment]
> > Se è presenta la scarica se no scala alla prima migliore
> 
> Quindi scarica direttamente a 1080p se non c'è un altra qualità (c'è ad altre qualità)

Si esatto, ti serviva una risoluzione più bassa o più alta? se è presente [1080, 720] scaricare 1080, se è presente [720, 480] scaricare 720.

**Comment by Skulp55** [comment]
> > > Se è presenta la scarica se no scala alla prima migliore
> > 
> > Quindi scarica direttamente a 1080p se non c'è un altra qualità (c'è ad altre qualità)
> 
> Si esatto, ti serviva una risoluzione più bassa o più alta? se è presente [1080, 720] scaricare 1080, se è presente [720, 480] scaricare 720.

Più bassa (c'è 1080, 720 e 480)

**Comment by Arrowar** [comment]
Quindi volevi scaricarli tutti in 480p ?

**Comment by Skulp55** [comment]
> Quindi volevi scaricarli tutti in 480p ?

Si

**Comment by Skulp55** [comment]
> > Quindi volevi scaricarli tutti in 480p ?
> 
> Si

e devo aspettare un aggiornamento per farlo?

**Comment by Arrowar** [comment]
No devi cambiare questa funzione https://github.com/Ghost6446/StreamingCommunity_api/blob/main/Src/Api/film.py e questa https://github.com/Ghost6446/StreamingCommunity_api/blob/main/Src/Api/tv.py in quest'altra: 
`

def select_quality(json_win_param):

    return "480p"

    if json_win_param['token1080p']:
        return "1080p"
    elif json_win_param['token720p']:
        return "720p"
    elif json_win_param['token480p']:
        return "480p"
    else:
        return "360p"

`, da def a return "360p"

**Comment by Skulp55** [comment]
> No devi cambiare questa funzione https://github.com/Ghost6446/StreamingCommunity_api/blob/main/Src/Api/film.py e questa https://github.com/Ghost6446/StreamingCommunity_api/blob/main/Src/Api/tv.py in quest'altra: `
> 
> def select_quality(json_win_param):
> 
> ```
> return "480p"
> 
> if json_win_param['token1080p']:
>     return "1080p"
> elif json_win_param['token720p']:
>     return "720p"
> elif json_win_param['token480p']:
>     return "480p"
> else:
>     return "360p"
> ```
> 
> `, da def a return "360p"

su tv.py non funziona :(

**Comment by Skulp55** [comment]
> return "480p"
> 
> if json_win_param['token1080p']:
>     return "1080p"
> elif json_win_param['token720p']:
>     return "720p"
> elif json_win_param['token480p']:
>     return "480p"
> else:
>     return "360p"

![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/111526859/465c8e9d-f585-4d21-8ea1-260465f6f19a)
 il problema è alla linea return e non si apre più

**Comment by Arrowar** [comment]
Devi dare un tab a tutto dal primo return all'ultimo

**Comment by Skulp55** [comment]
> Devi dare un tab a tutto dal primo return all'ultimo

non funziona

**Comment by Skulp55** [comment]
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/111526859/e7b4f458-0cf1-4dd2-bd96-834b6570c360)

**Comment by Arrowar** [comment]
Anche uno agli ultimo 4 return
