### ISSUE TITLE
Original File Option

### ISSUE THREAD

**Issue by Cohvir** [AstraeLabs/VibraVid#51]
Ciao, ti posso consigliare di far scegliere all'utente prima del download se vuole mantenere il file originale (`.ts`) o se lo preferisce nel più comune `.mp4`.

**Comment by Arrowar** [comment]
Con i file ts non puoi guardatelo intero, sono frane di video e solitamente sono più di 500, dovevi fare qualcosa di particolare ai file ts ?

**Comment by Cohvir** [comment]
Lo scopo era solo quello di saltare la conversione in `mp4` per velocizzare il processo. I file TS dovrebbero essere uniti comunque in uno solo come già avviene (se non sbaglio).

**Comment by Arrowar** [comment]
Ok quindi anche per l'audio ?

**Comment by Cohvir** [comment]
> Ok quindi anche per l'audio ?

Si, Esattamente!
