### ISSUE TITLE
Crash mentre provo a scaricare 2 episodi

### ISSUE THREAD

**Issue by jacopeste05** [AstraeLabs/VibraVid#52]
Stavo cercando di scaricare l'episodio 7 e l'episodio 9 della sesta stagione di "Formula 1 Drive to Survive" ma crasha. Gli altri episodi si sono scaricati senza problemi

**Comment by Ghost6446** [comment]
Che errore ?

**Comment by Arrowar** [comment]
Riprova ora, scarica manualemente l'ultima versione e cambia sostituisci tutti i file.
