### ISSUE TITLE
Crash su Macos su ogni contenuto

### ISSUE THREAD

**Issue by giauen** [AstraeLabs/VibraVid#53]
Ogni volta che provo a scaricare un contenuto, l'app crasha nel momento in cui cerca di creare la struttura di cartelle e sottocartelle in cui mettere i file.

`File "/StreamingCommunity_api/Src/Lib/FFmpeg/my_m3u8.py", line 466, in download_m3u8
    os.makedirs("\\".join(path[:-1]), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: ''`

Ho risolto sostituendo la riga 462 di my_m3u8.py con 
`path = os.path.expanduser(output_filename)`

**Comment by Arrowar** [comment]
Ok perfetto grazie mille
