### ISSUE TITLE
Lo script non riesce a scaricare più ne film ne episodi di serie tv

### ISSUE THREAD

**Issue by Forgottone** [AstraeLabs/VibraVid#55]
Ogni volta che provo a scaricare qualcosa ricevo sempre questo errore: " Error saving MP4: None  "

**Comment by Arrowar** [comment]
Riprova ora, scarica manualemente l'ultima versione e cambia sostituisci tutti i file.

**Comment by Forgottone** [comment]
Ho appena provato, il problema si è presentato di nuovo dopo aver scaricato 7episodi di una serie

**Comment by Forgottone** [comment]
![Uploading Screenshot_1.png…]()

**Comment by Arrowar** [comment]
Nome della serie ed ep ?

**Comment by Forgottone** [comment]
Agents of shield stagione 5, ma ieri l'errore si presentava con diverse serie e film, ora sto riprovando a scaricarla ma sembra procedere senza problemi

**Comment by Arrowar** [comment]
Ok se da ancora questo errore, riprova dovrebbe andare, per il momento.
