### ISSUE TITLE
Output Folder Option

### ISSUE THREAD

**Issue by Cohvir** [AstraeLabs/VibraVid#57]
Avere la possibilità di aggiungere una cartella di output invece di avere l'hard-coded `videos` sarebbe utile a chi ha necessità di copiare i video in una cartella specifica ad ogni download. Utilizzare un file config anche qui sarebbe comodo.

**Comment by Arrowar** [comment]
Si ora ho capito, lo sto facendo ma ci vuole ancora tempo da che sto riscrivendo tutto

**Comment by Cohvir** [comment]
Ciao Ghost, io sto implementando un sistema di config molto semplice. Se vuoi ti faccio pull request per farti risparmiare tempo. Purtroppo sul problema #51 non posso aiutarti perché non sono pratico in materia I/O di dati video.

**Comment by Arrowar** [comment]
Certo grazie mille.

**Comment by Arrowar** [comment]
Qualsiasi pull con logica è ben accetta.
