### ISSUE TITLE
No subtitle found on Movies

### ISSUE THREAD

**Issue by Cohvir** [AstraeLabs/VibraVid#59]
Quando provo a scaricare un film, lo script non trova alcun sottotitolo, mentre su StreamingCommunity sono disponibili.

[Esempio](https://streamingcommunity.report/watch/7927) di film con i sottotitoli.

Risultato:
![Result](https://github.com/Ghost6446/StreamingCommunity_api/assets/63691557/f2cda138-b9c9-4a77-a619-fe754cffea86)

Nessun problema con le serie tv.

**Comment by Fede14it** [comment]
Fixed #64
