### ISSUE TITLE
Config: audio and subtitles improvements

### ISSUE THREAD

**Issue by Cohvir** [AstraeLabs/VibraVid#62]
1. Un'opzione che permetta di abilitare la selezione "manuale" delle lingue audio tra quelle disponibili (attualmente è possibile scegliere la lingua, ma solamente una)
```json
{
  "audio_select_language": true
}
```
Permetterà all'utente di inserire l'input:
```
Choose which audio languages you want to download:

0 - Italiano
1 - English
2 - Français
...

Insert audio INDEX, or (*) to download all audios, or [1-2] for a range of audios, or [1,3,8] for multi-selection:
```

2. Un'opzione che permetta di scaricare determinati sottotitoli scegliendo tra le lingue disponibili (attualmente le scarica tutte in automatico)
```json
{
  "subtitles_select_language": true
}
```
```
Choose which subtitles you want to download:

0 - Italiano
1 - Italiano-forced
2 - Français
...

Insert subtitle INDEX, or (*) to download all subtitiles, or [1-2] for a range of subtitles or [1,3,8] for multi-selection:
```

Se la selezione "manuale" è attiva, un input, che agisce come quello per selezionare le serie e le stagioni, permetterà di scegliere quale lingua scaricare. Altrimenti, il comportamento di default sarà quello attuale, ovvero non richiedere l'input all'utente.

**Comment by Arrowar** [comment]
Certo stavo pensando insieme @Fede14it di scaricare anche tutte le tracce audio, quindi sarebbe un'ulteriore opzione. Un'altra cosa meglio un file .json per la configurazione o un .ini ?

**Comment by Fede14it** [comment]
Io direi di continuare su quel json

**Comment by Cohvir** [comment]
> Certo stavo pensando insieme @Fede14it di scaricare anche tutte le tracce audio, quindi sarebbe un'ulteriore opzione. Un'altra cosa meglio un file .json per la configurazione o un .ini ?

@Ghost6446 avevi qualche motivo in particolare per l'utilizzo di un file `.ini`?

**Comment by Arrowar** [comment]
> > Certo stavo pensando insieme @Fede14it di scaricare anche tutte le tracce audio, quindi sarebbe un'ulteriore opzione. Un'altra cosa meglio un file .json per la configurazione o un .ini ?
> 
> @Ghost6446 avevi qualche motivo in particolare per l'utilizzo di un file `.ini`?


No in particolare nessuno, avevo già fatto tempo fa una classe del genere ma non penso sia tropo difficile riorganizzarsi per un file .json.

**Comment by Fede14it** [comment]
Comunque cosa da fare molto urgente è quel my_m3u8 andrebbero tolte le
funzioni in più e inviata a lui solo la playlist, dopo di che si prende
video con maggiore risoluzione, audio con la lingua giusta e sottotitoli.
Si scarica tutto unisce e via

Il Mar 5 Mar 2024, 16:24 Ghost ***@***.***> ha scritto:

**Comment by Cohvir** [comment]
> No in particolare nessuno, avevo già fatto tempo fa una classe del genere ma non penso sia tropo difficile riorganizzarsi per un file .json.

L'unica cosa (**non da poco**) che, se non sbaglio, un file `.ini` può dare rispetto a un `json`, è la facilità con cui un utente medio può cambiare il file senza prestare troppa attenzione alle regole di sintassi. JSON è antipatico con le sue parentesi.
Ma siamo d'accordo che non sia una priorità al momento.

> Comunque cosa da fare molto urgente è quel my_m3u8 andrebbero tolte le funzioni in più e inviata a lui solo la playlist, dopo di che si prende video con maggiore risoluzione, audio con la lingua giusta e sottotitoli. Si scarica tutto unisce e via

Sono d'accordo, pulizia delle funzioni e variabili inutilizzate, insieme a rendere il codice riutilizzabile (non ripetuto) può aiutare. Io nell'ultimo pull #63 ho commentato alcune variabili e funzioni non utilizzate ma non le ho rimosse del tutto perché non so se effettivamente potessero servire in futuro a chi le ha aggiunte.

**Comment by Fede14it** [comment]
Comunque @Ghost6446 sarebbe bello creare un discord dove si puó chattare e organizzarsi per le cose da fare

**Comment by Arrowar** [comment]
> Comunque @Ghost6446 sarebbe bello creare un discord dove si puó chattare e organizzarsi per le cose da fare

Domani lo creo e aggiungo il link

**Comment by Arrowar** [comment]
> Comunque @Ghost6446 sarebbe bello creare un discord dove si puó chattare e organizzarsi per le cose da fare

Creato: https://discord.gg/RtHRvRXU

**Comment by Cohvir** [comment]
@Ghost6446 hai chiuso l'issue perché hai creato il discord o perché sono state implementate le opzioni? 😅

**Comment by Arrowar** [comment]
> @Ghost6446 hai chiuso l'issue perché hai creato il discord o perché sono state implementate le opzioni? 😅

Entrambe, sto implementando la logica ma dato che sono molte le opzioni serve tempo.

**Comment by Ponseh** [comment]
@Ghost6446 salve, il progetto è stupendo, potrei l'avanzamento della feature in questione? grazie mille

**Comment by Ponseh** [comment]
@Ghost6446 salve, il progetto è stupendo, potrei sapere l'avanzamento della feature in questione? grazie mille

**Comment by Arrowar** [comment]
> @Ghost6446 salve, il progetto è stupendo, potrei sapere l'avanzamento della feature in questione? grazie mille

Completate entrambe, ora devo solo trovare il tempo per sistemare tutte i vari commenti ed log, e dopo dovrebbe essere operativa la nuova versione. Ho cambiato quasi tutti i file quindi ci vorrà ancora un po' di tempo, questa è la nuova struttura. 
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/62809003/c883f091-73ad-4e25-923c-547e87a53aac)
Ho aggiungo molte più funzioni e sistemato quelle che non andavano dall versione 1
