### ISSUE TITLE
Error muxing video output

### ISSUE THREAD

**Issue by Forgottone** [AstraeLabs/VibraVid#66]
![Screenshot_1](https://github.com/Ghost6446/StreamingCommunity_api/assets/112017382/63330b6d-6fa5-4a40-a557-6473aa2fce0e)

**Comment by Cohvir** [comment]
Ciao @Forgottone, potresti aggiungere qualche dettaglio?

1. L'errore si presenta solo con un certo episodio, o una certa serie?
2. Sistema operativo?
3. Stai utilizzando l'ultima versione di StreamingCommunity_api?

**Comment by Forgottone** [comment]
Sto usando l'ultima versione, l'errore di verifica su 3 episodi della serie tv, il 10, 22,23,24 (stagione 9)
sono su win 10

**Comment by Arrowar** [comment]
> Sto usando l'ultima versione, l'errore di verifica su 3 episodi della serie tv, il 10, 22,23,24 (stagione 9) sono su win 10

Riprova a scaricare il nuovo commit, non è una vera e propria soluzione, ma nonostance ciò scaricare video e audio e gli sincronizza.

**Comment by Cohvir** [comment]
> > Sto usando l'ultima versione, l'errore di verifica su 3 episodi della serie tv, il 10, 22,23,24 (stagione 9) sono su win 10
> 
> Riprova a scaricare il nuovo commit, non è una vera e propria soluzione, ma nonostance ciò scaricare video e audio e gli sincronizza.

Questo errore capita anche a me in quegli episodi specifici, sicuramente sarà dovuto al modo in cui forniscono i file (diverso dal solito). Sarebbe da analizzare per evitare succeda con più contenuti

**Comment by Arrowar** [comment]
> > > Sto usando l'ultima versione, l'errore di verifica su 3 episodi della serie tv, il 10, 22,23,24 (stagione 9) sono su win 10
> > 
> > 
> > Riprova a scaricare il nuovo commit, non è una vera e propria soluzione, ma nonostance ciò scaricare video e audio e gli sincronizza.
> 
> Questo errore capita anche a me in quegli episodi specifici, sicuramente sarà dovuto al modo in cui forniscono i file (diverso dal solito). Sarebbe da analizzare per evitare succeda con più contenuti

Si anche a me capita, penso sia dovuto alla versione: https://trac.ffmpeg.org/ticket/6437

**Comment by Cohvir** [comment]
> Si anche a me capita, penso sia dovuto alla versione: https://trac.ffmpeg.org/ticket/6437

Vedo che è un problema di 7 anni fa. Strano. Ma non capisco cosa hanno proprio quegli episodi di strano che causa l'errore ad ffmpeg
