### ISSUE TITLE
Episode of season error 404

### ISSUE THREAD

**Issue by Forgottone** [AstraeLabs/VibraVid#67]
![Screenshot_2](https://github.com/Ghost6446/StreamingCommunity_api/assets/112017382/e061e910-07d0-4b89-b360-83370a1d3e7e)

Questo errore si presenta con ogni contenuto che provo a scaricare
sto usando l'ultima versione

**Comment by Fede14it** [comment]
Come puoi vedere dall'immagine qui sotto non esiste il primo episodio.
Ora tento un fix ma per ora ti direi di selezionare la 5^stagione e scaricare [2-24]
Potresti fornire altre stagioni/serie dove riscontri questo problema?
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/115009551/4fdb6d2e-bd7e-475e-884c-8fe4bb24a1ab)
