### ISSUE TITLE
Ffmpeg error

### ISSUE THREAD

**Issue by colodev25** [AstraeLabs/VibraVid#7]
![Screenshot 2024-01-05 222638](https://github.com/Ghost6446/StreamingCommunity_api/assets/155778890/d7ae9b47-a905-45ea-9550-dde0bed7c831)

**Comment by Arrowar** [comment]
Prova a togliere - ed i . dal nome della cartella do streamingcomunityapi

**Comment by colodev25** [comment]
ora funziona tutto, grazie mille (ho rinominato streamingcommunityapi 061)

**Comment by Arrowar** [comment]
Perfetto, togli anche gli spazzi, sono i caratteri che danno più problemi
