### ISSUE TITLE
Missing audio ...

### ISSUE THREAD

**Issue by nelletto** [AstraeLabs/VibraVid#71]
Ciao, provando a scaricare la Serie Halo va a buon fine ma il file risultante manca completamente della traccia audio. Ho provato sia con il lettore di Windows che con VLC

**Comment by loret010** [comment]
Anche a me.

**Comment by loret010** [comment]
@Ghost6446 Potresti dirci come risolvere il problema?

**Comment by loret010** [comment]
A me è capitato ma solamente perchè avevo chiuso il CMD ancora prima che avesse finito.

**Comment by Arrowar** [comment]
> Ciao, provando a scaricare la Serie Halo va a buon fine ma il file risultante manca completamente della traccia audio. Ho provato sia con il lettore di Windows che con VLC

Appena prova halo s1:e1 e funziona sia video che audio.
