### ISSUE TITLE
Make `keep_specific_items` function safe or prompt for confirmation

### ISSUE THREAD

**Issue by nanaki82** [AstraeLabs/VibraVid#74]
I run `update` from another directory and I lost all the files/dir! Maybe it's better to inform the user all the files in the current directory will be deleted

**Comment by Arrowar** [comment]
> I run `update` from another directory and I lost all the files/dir! Maybe it's better to inform the user all the files in the current directory will be deleted

I write it not to delete all videos directory, but I will fix it. Delete videos directory or all directory ?

**Comment by nanaki82** [comment]
If I read correctly the code, It deletes all the files/directory except `upload.py` and `videos` directory.

The problem was that I use the script inside another directory where I store all my files downloaded 😞

**Comment by Arrowar** [comment]
I know, i will add a mesaage to ask to continue, normally all the file need to be stare in videos folder.
