### ISSUE TITLE
Error 409

### ISSUE THREAD

**Issue by Topicform** [AstraeLabs/VibraVid#8]
Buonasera a tutti, il progetto è molto allettante, diciamo che su 5 movie scaricati, 3 sono andati a buon fine,   il quarto era privo di traccia audio ed il quinto è risultato scomposto delle sue parti (i titoli di testa a metà film e altre parti iniziali spostate)... Grazie dell'attenzione e buon anno.

**Comment by Arrowar** [comment]
Grazie mille, provi ora con la modifica cbe ho fatto in 5 minuti, il prossmo aggiornamento arriverà settimana prossima se necessario. Per il momento sono solo io che ci lavoro

**Comment by Ghost6446** [comment]
Al massimo prova a scrivermi i titoli o episodi che hanno problemi e appena ho due minuti gli do una controllata.

**Comment by Arrowar** [comment]
Al massimo prova a scrivermi i titoli o episodi che hanno problemi e appena ho due minuti gli do una controllata.

**Comment by Topicform** [comment]
Buonasera,ok attenderò la nuova versione, al momento la informo che l'ultima release fatta addirittura si chiude la console subito dopo ave selezionato il numero corrispondente al titolo scelto... no problem attendo fiducioso...senza fretta. Saluti.

**Comment by Arrowar** [comment]
Ora non ci dovrebbero essere più problemi di alcun tipo

**Comment by Topicform** [comment]
Buongiorno, mi spiace davvero dirle che non è cambiato nulla, direi quasi che la prima versione qualche titolo son riuscito a scaricarlo. Le dico che non appena seleziono il numero corrispondente al titolo scelto, parte il download e dopo qualche secondo si interrompe, lasciando nella dir Temp alcuni file ts... Se vuole una indicazione maggiore, ho provato a scaricare il film "Maestro". Grazie per l'attenzione, le ripeto non ho alcuna fretta e la ringrazio per il tempo dedicato. Saluti.

**Comment by Topicform** [comment]
Chiedo scusa, le segnalo l'errore a piè di pagina nel cmd...  "Index error: List index out of range" Saluti.

**Comment by Topicform** [comment]
Osservazione ultima chiedendo scusa dei troppi inoltri... .:) Allora il titolo "Le strade del male" è stato scaricato perfettamente, quindi presumo che non sia dovuto ad un inghippo del suo script, ma, a qualche problemino su altri titoli che ahimè per qualche strambo motivo non si lasciano scaricare. A lei le conclusioni. Buona domenica e ancora grazie.

**Comment by Arrowar** [comment]
Di niente, ora dovrebbe andare

**Comment by Topicform** [comment]
Ok perfetto in bocca al lupo😉
