### ISSUE TITLE
Error 403 when trying to download

### ISSUE THREAD

**Issue by teocavaa** [AstraeLabs/VibraVid#83]
Hi, I've never had an issue but now it's giving me and 403 error when downloading. I've tried with VPN and normal IP and is not working

**Comment by Arrowar** [comment]
> Hi, I've never had an issue but now it's giving me and 403 error when downloading. I've tried with VPN and normal IP and is not working

They implement cloudfare with request to iframe ..., next week I create a new version.

**Comment by Arrowar** [comment]
> Hi, I've never had an issue but now it's giving me and 403 error when downloading. I've tried with VPN and normal IP and is not working

Now work
