### ISSUE TITLE
error when customizing output folder

### ISSUE THREAD

**Issue by giauen** [AstraeLabs/VibraVid#85]
Il programma crasha nel momento in cui viene modificato il percorso di output. In particolare, nel momento in cui ffmpeg cerca di unire la traccia audio, la cerca nel path `videos/audio.mp4`, non considerando il path specificato nel file .config

Qui l'inizializzazione della classe con il path di default https://github.com/Ghost6446/StreamingCommunity_api/blob/main/Src/Lib/FFmpeg/my_m3u8.py#L338

**Comment by Arrowar** [comment]
Oggi vedo di risolvere
