### ISSUE TITLE
Downloading FFmpeg... Unable to download or add FFmpeg to the PATH.

### ISSUE THREAD

**Issue by brazoayeye** [AstraeLabs/VibraVid#87]
I tried to use it on ubuntu, installed python3.11 and 

`sudo python3.11 run.py `

but I have this error

```
Downloading FFmpeg...
Unable to download or add FFmpeg to the PATH.
```

But I ping google without problems.

**Comment by Arrowar** [comment]
Try remove the control on run.py, the name is check_ffmpeg, ubuntu have ffmpeg by default but in windows no. I will change the code.
https://github.com/Ghost6446/StreamingCommunity_api/blob/main/run.py#L37, remove this line.

**Comment by brazoayeye** [comment]
Now it starts, but when trying to download i have
An error occurred: No module named '_cffi_backend'

multiple times


PS: it downloaded ffmpeg/ffmpeg.zip but didn't extracted it

**Comment by Arrowar** [comment]
If you remove that line, the script dont need to install it.

**Comment by brazoayeye** [comment]
_cffi_backend seems solved with 
`sudo python3.11 -m pip install cffi`

I solved also the previous problem with
`sudo apt-get install ffmpeg`

**Comment by Arrowar** [comment]
Perfect
