### ISSUE TITLE
carattere speciale

### ISSUE THREAD

**Issue by dizplayy** [AstraeLabs/VibraVid#92]
serie "mr inbetween", stagione 1, episodio 1
"il tipo della pipì"
ad un certo punto della procedura esce l'errore screenshottato e non avviene il join.
![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/11553812/dccf3b7a-2fb7-43b9-9075-6d3a7e106332)

**Comment by Arrowar** [comment]
Ok oggi pubblico l'update.

**Comment by Arrowar** [comment]
Sistemato
