### ISSUE TITLE
ENV Temp multipiattaforma

### ISSUE THREAD

**Issue by tgiachi** [AstraeLabs/VibraVid#94]
https://github.com/Ghost6446/StreamingCommunity_api/blob/bf7153214f03c748ee0eefd8629a37ecf567ec59/Src/Lib/Request/user_agent.py#L83C30-L83C50

ciao!,
Qui c'e' un bug in caso viene lanciato su linux o osx:
la ENV $TEMP e' solo presente su windows, ti merita usare:
```
import tempfile

print tempfile.gettempdir() 
```

Per prendere la directory temporanea del sistema operativo!

**Comment by Arrowar** [comment]
> https://github.com/Ghost6446/StreamingCommunity_api/blob/bf7153214f03c748ee0eefd8629a37ecf567ec59/Src/Lib/Request/user_agent.py#L83C30-L83C50
> 
> ciao!, Qui c'e' un bug in caso viene lanciato su linux o osx: la ENV $TEMP e' solo presente su windows, ti merita usare:
> 
> ```
> import tempfile
> 
> print tempfile.gettempdir() 
> ```
> 
> Per prendere la directory temporanea del sistema operativo!

Grazie mille corrego subito, avendo provato a scriverla da solo non avevo pensato a questo caso.

**Comment by Arrowar** [comment]
Aggiunto

**Comment by tgiachi** [comment]
di niente grazie a te!
